COMMANDS = {
    "init": (),
    "inventory-install": (),
    "csr-trust-install": (),
    "csr-recover": (),
    "offline-csr": ("approve", "sign"),
    "certificate-export": ("publish", "resolve"),
    "csr-outcome": ("publish", "resolve"),
    "csr-candidate": ("verify", "finalize", "abandon"),
    "root-create": (),
    "intermediate-create": (),
    "service-issue": (),
    "service-renew": (),
    "service-recover": (),
    "service-verify": (),
    "list-expiry": (),
    "print-cert": (),
    "export-ansible": (),
    "backup": (),
    "custody-report": (),
    "ca-passphrase-verify": (),
    "ca-rollover": ("migrate", "status", "prepare", "recover"),
}
