COMMANDS = {
    "init": (),
    "inventory-install": (),
    "csr-trust-install": (),
    "csr-recover": (),
    "offline-csr": ("approve", "sign"),
    "offline-workspace": ("init",),
    "certificate-export": ("publish", "resolve"),
    "csr-outcome": ("publish", "resolve"),
    "direct-exchange": (
        "request-pull",
        "evidence-pull",
        "response-push",
        "outcome-push",
    ),
    "gitlab-package": ("publish", "download", "publish-request"),
    "csr-candidate": ("verify", "finalize", "abandon"),
    "root-create": (),
    "intermediate-create": (),
    "service-issue": (),
    "service-renew": (),
    "service-recover": (),
    "service-verify": (),
    "list-expiry": (),
    "print-cert": (),
    "export-ansible": (),
    "backup": (),
    "custody-report": (),
    "ca-passphrase-verify": (),
    "ca-rollover": ("migrate", "status", "prepare", "recover"),
}
