SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
COMMON_PATH=${PLATFORM_TOOLS_LIB_DIR:-}
if [[ -n $COMMON_PATH ]]; then COMMON_PATH=${COMMON_PATH}/platform-pki-common.sh
elif [[ -r ${SCRIPT_DIR}/../lib/platform-pki-common.sh ]]; then COMMON_PATH=${SCRIPT_DIR}/../lib/platform-pki-common.sh
else COMMON_PATH=${PLATFORM_TOOLS_SHARE_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/platform-tools}/lib/platform-pki-common.sh; fi
[[ -r $COMMON_PATH ]] || { printf '[ERROR] platform-pki-common.sh not found\n' >&2; exit 1; }
# shellcheck source=../../../../lib/platform-pki-common.sh disable=SC1091
source "$COMMON_PATH"
pki_reject_repeated_options --namespace --pki-dir --transaction --action --yes

NAMESPACE=${args[--namespace]:-$(pki_default_namespace)}; PKI_DIR=${args[--pki-dir]:-}
TRANSACTION=${args[--transaction]}; ACTION=${args[--action]}; YES=false; [[ -v args[--yes] ]] && YES=true
NAMESPACE=$(pki_expand_path "$NAMESPACE"); PKI_DIR=${PKI_DIR:-${NAMESPACE}/pki}; PKI_DIR=$(pki_expand_path "$PKI_DIR")
[[ $TRANSACTION =~ ^(migrate|root-bootstrap|intermediate-bootstrap|prepare-root|prepare-intermediate)-[0-9]{8}-[0-9]{6}-[0-9]+$ ]] || pki_die 'Recovery transaction ID is invalid'
if [[ $YES != true ]]; then
  [[ -t 0 ]] || pki_die 'Recovery requires a TTY or --yes'
  printf 'Type recover %s %s to continue: ' "$TRANSACTION" "$ACTION" >&2
  IFS= read -r confirmation; [[ $confirmation == "recover $TRANSACTION $ACTION" ]] || pki_die 'Recovery confirmation did not match'
fi
pki_require_pki_dir; pki_prepare_control_state
ROOT_LOCK=$(pki_root_operation_lock); INTERMEDIATE_LOCK=$(pki_intermediate_operation_lock); INVENTORY_LOCK=$(pki_inventory_operation_lock); EXPORT_LOCK=$(pki_export_operation_lock)
finish_recover() { local status=$?; trap - EXIT; [[ ${EXPORT_LOCK_HELD:-false} != true ]] || pki_release_operation_lock "$EXPORT_LOCK" || status=1; [[ ${INVENTORY_LOCK_HELD:-false} != true ]] || pki_release_operation_lock "$INVENTORY_LOCK" || status=1; [[ ${INTERMEDIATE_LOCK_HELD:-false} != true ]] || pki_release_operation_lock "$INTERMEDIATE_LOCK" || status=1; [[ ${ROOT_LOCK_HELD:-false} != true ]] || pki_release_operation_lock "$ROOT_LOCK" || status=1; exit "$status"; }
trap finish_recover EXIT
pki_acquire_operation_lock "$ROOT_LOCK" 'root CA operation'; ROOT_LOCK_HELD=true
pki_acquire_operation_lock "$INTERMEDIATE_LOCK" 'intermediate CA operation'; INTERMEDIATE_LOCK_HELD=true
pki_acquire_operation_lock "$INVENTORY_LOCK" 'inventory operation'; INVENTORY_LOCK_HELD=true
pki_acquire_operation_lock "$EXPORT_LOCK" 'export operation'; EXPORT_LOCK_HELD=true
JOURNAL=$(pki_recovery_journal); MARKER=$(pki_recovery_marker)
if [[ ! -e $JOURNAL && ! -L $JOURNAL ]]; then
  TERMINAL_RECEIPT=$(pki_terminal_receipt "$TRANSACTION")
  pki_read_state_record "$MARKER" 'PKI recovery marker'
  [[ ${#PKI_RECORD[@]} -eq 3 && ${PKI_RECORD[transaction]:-} == "$TRANSACTION" && ${PKI_RECORD[operation]:-} == rollover-prepare && ${PKI_RECORD[terminal_outcome]:-} =~ ^(resumed|rolled-back)$ ]] || pki_die 'Recovery marker does not describe terminal preparation cleanup'
  marker_outcome=${PKI_RECORD[terminal_outcome]}
  pki_read_state_record "$TERMINAL_RECEIPT" 'Preparation terminal receipt'
  [[ ${#PKI_RECORD[@]} -eq 5 && ${PKI_RECORD[transaction]:-} == "$TRANSACTION" && ${PKI_RECORD[operation]:-} == rollover-prepare && ${PKI_RECORD[terminal_outcome]:-} == "$marker_outcome" ]] || pki_die 'Preparation terminal receipt does not match the recovery marker'
  pki_require_file_identity "$MARKER" "${PKI_RECORD[marker_identity]}" 'PKI recovery marker'
  [[ $ACTION == resume && $marker_outcome == resumed || $ACTION == rollback && $marker_outcome == rolled-back ]] || pki_die 'Recovery action does not match the terminal preparation outcome'
  pki_remove_identity_file "$MARKER" "${PKI_RECORD[marker_identity]}" terminal-marker || pki_die 'Recovery marker changed before terminal unlink'; pki_ok "Completed terminal cleanup for $TRANSACTION"; exit 0
fi
pki_read_state_record "$JOURNAL" 'PKI recovery journal'
[[ ${PKI_RECORD[transaction]:-} == "$TRANSACTION" ]] || pki_die 'Recovery journal does not describe the requested transaction'
[[ ${PKI_RECORD[committed]:-} == false || ${PKI_RECORD[operation]:-} == rollover-prepare && ${PKI_RECORD[committed]:-} == true ]] || pki_die 'Recovery action is not valid for the journaled transaction state'
recover_fault() { [[ ${PLATFORM_PKI_RECOVER_CRASH_AT:-} != "$1" ]] || kill -KILL "$$"; }
write_loaded_journal() {
  local phase=$1 committed=${2:-false} key value content=''
  PKI_RECORD[phase]=$phase; PKI_RECORD[committed]=$committed
  while IFS= read -r key; do value=${PKI_RECORD[$key]}; content+="$key=$value
"; done < <(printf '%s\n' "${!PKI_RECORD[@]}" | LC_ALL=C sort)
  pki_write_journal "$JOURNAL" "$content"
}
checkpoint_recovery() { PKI_RECORD[recovery_step]=$1; write_loaded_journal recovering; recover_fault "$1"; }
finish_recovered_preparation() {
  local outcome=$1 expected_action journal_identity marker_identity receipt
  if [[ $outcome == resumed ]]; then expected_action=resume; else expected_action=rollback; fi
  [[ $ACTION == "$expected_action" ]] || pki_die 'Recovery action does not match the terminal preparation outcome'
  PKI_RECORD[recovery_action]=$ACTION; PKI_RECORD[terminal_outcome]=$outcome; PKI_RECORD[recovery_step]=terminal-transaction-pending
  write_loaded_journal terminal-cleanup true
  pki_atomic_write "$MARKER" "transaction=$TRANSACTION
operation=rollover-prepare
terminal_outcome=$outcome
"
  recover_fault terminal-transaction-pending
  if [[ -d $TXN_DIR && ${PKI_RECORD[transaction_tree_manifest]:-none} != none ]]; then
    pki_remove_manifested_tree "$TXN_DIR" "${PKI_RECORD[transaction_identity]}" "$(dirname -- "$TXN_DIR")" "${PKI_RECORD[transaction_tree_manifest]}" "${PKI_RECORD[transaction_tree_manifest_identity]}" "${PKI_RECORD[transaction_tree_manifest_sha256]}" || pki_die 'Cannot remove preparation transaction staging'
  elif [[ -d $TXN_DIR ]]; then
    [[ ${PKI_RECORD[transaction_identity]} == none || -z $(find "$TXN_DIR" -mindepth 1 -print -quit) ]] || pki_die 'Incomplete preparation transaction has no exact cleanup manifest'
    rmdir -- "$TXN_DIR" || pki_die 'Cannot remove empty incomplete preparation transaction staging'; pki_fsync "$(dirname -- "$TXN_DIR")"
  elif [[ -e $TXN_DIR || -L $TXN_DIR ]]; then pki_die 'Preparation transaction staging has an unsafe replacement'; fi
  PKI_RECORD[recovery_step]=terminal-transaction-done; write_loaded_journal terminal-cleanup true; recover_fault terminal-transaction-done
  PKI_RECORD[recovery_step]=terminal-journal-pending; write_loaded_journal terminal-cleanup true; recover_fault terminal-journal-pending
  journal_identity=$(pki_file_identity "$JOURNAL"); marker_identity=$(pki_file_identity "$MARKER"); receipt=$(pki_terminal_receipt "$TRANSACTION")
  pki_atomic_write "$receipt" "transaction=$TRANSACTION
operation=rollover-prepare
terminal_outcome=$outcome
journal_identity=$journal_identity
marker_identity=$marker_identity
"
  pki_remove_identity_file "$JOURNAL" "$journal_identity" terminal-journal || pki_die 'Recovery journal changed before terminal unlink'; recover_fault terminal-journal-done
  pki_remove_identity_file "$MARKER" "$marker_identity" terminal-marker || pki_die 'Recovery marker changed before terminal unlink'
}
file_state_allowed() {
  local path=$1 label=$2 current full expected
  shift 2
  current=$(pki_file_identity_or_absent "$path"); full=$current
  [[ $current == absent ]] || full=$(pki_file_identity "$path")
  for expected in "$@"; do [[ $current != "$expected" && $full != "$expected" ]] || return 0; done
  pki_die "$label is not in a journaled identity state"
}
verify_bound_file() { local path=$1 identity=$2 digest=$3 label=$4 actual; pki_require_file_identity "$path" "$identity" "$label"; actual=$(sha256sum "$path"); [[ ${actual%% *} == "$digest" ]] || pki_die "$label digest changed"; }
if [[ ${PKI_RECORD[operation]:-} == rollover-prepare ]]; then
  required_fields=(schema operation transaction type phase committed recovery_action recovery_step terminal_outcome active_root active_intermediate active_manifest active_identity candidate_root candidate_intermediate candidate_root_dir candidate_intermediate_dir candidate_root_identity candidate_intermediate_identity candidate_root_key_identity candidate_root_cert_identity candidate_root_cert_sha256 candidate_intermediate_key_identity candidate_intermediate_csr_identity candidate_intermediate_cert_identity candidate_intermediate_cert_sha256 candidate_chain_identity candidate_chain_sha256 candidate_root_tree_manifest candidate_root_tree_manifest_identity candidate_root_tree_manifest_sha256 candidate_intermediate_tree_manifest candidate_intermediate_tree_manifest_identity candidate_intermediate_tree_manifest_sha256 root_stage_tree_manifest root_stage_tree_manifest_identity root_stage_tree_manifest_sha256 stage_tree_manifest stage_tree_manifest_identity stage_tree_manifest_sha256 transaction_tree_manifest transaction_tree_manifest_identity transaction_tree_manifest_sha256 transaction_tree_manifest_sequence transaction_tree_manifest_pending transaction_tree_manifest_pending_destination transaction_tree_manifest_pending_identity transaction_tree_manifest_pending_sha256 transaction_dir transaction_identity stage_dir stage_identity root_stage root_stage_identity root_stage_private_identity root_stage_key_identity intermediate_stage_identity intermediate_stage_private_identity long_stage long_dir long_identity long_manifest_identity long_manifest_sha256 long_tree_manifest long_tree_manifest_identity long_tree_manifest_sha256 trust_snapshot_identity pointer pointer_identity backup_receipt receipt_identity backup_session backup_session_original_identity backup_session_identity root_reservation root_reservation_reserved_identity root_reservation_consumed_identity root_reservation_abandoned_identity intermediate_reservation intermediate_reservation_reserved_identity intermediate_reservation_consumed_identity intermediate_reservation_abandoned_identity root_fingerprint intermediate_fingerprint root_expiry intermediate_expiry trust_bundle_sha256 trust_snapshot_sha256 trust_source trust_source_identity issued_serial root_mutated)
  for field in "${required_fields[@]}"; do [[ -v PKI_RECORD[$field] ]] || pki_die "Preparation recovery journal is missing field: $field"; done
  for key in index index_attr serial crlnumber index_old index_attr_old serial_old crlnumber_old newcert; do for suffix in pre_identity post_identity backup_identity rollback_identity source_identity; do field="root_${key}_${suffix}"; [[ -v PKI_RECORD[$field] ]] || pki_die "Preparation recovery journal is missing field: $field"; done; done
  [[ ${PKI_RECORD[schema]} == 5 && ${PKI_RECORD[type]} =~ ^(root|intermediate)$ && ${PKI_RECORD[transaction_tree_manifest_sequence]} =~ ^[0-9]+$ ]] || pki_die 'Preparation recovery journal schema is unsupported'
  TYPE=${PKI_RECORD[type]}; TXN_DIR=${PKI_RECORD[transaction_dir]}; STAGE_DIR=${PKI_RECORD[stage_dir]}; LONG_STAGE=${PKI_RECORD[long_stage]}; LONG_DIR=${PKI_RECORD[long_dir]}; POINTER=${PKI_RECORD[pointer]}; ROOT_RESERVATION=${PKI_RECORD[root_reservation]}; INT_RESERVATION=${PKI_RECORD[intermediate_reservation]}; ROOT_DIR=${PKI_RECORD[candidate_root_dir]}; INT_DIR=${PKI_RECORD[candidate_intermediate_dir]}
  [[ $TRANSACTION =~ ^prepare-${TYPE}-[0-9]{8}-[0-9]{6}-[0-9]+$ && $TXN_DIR == "$PKI_DIR/state/rollover/$TRANSACTION" && $LONG_DIR == "$(pki_rollover_transaction_dir "$TRANSACTION")" && $LONG_STAGE == "$TXN_DIR/rollover-state" && ( ${PKI_RECORD[stage_tree_manifest]} == none || ${PKI_RECORD[stage_tree_manifest]} == "$TXN_DIR/stage-tree.manifest" ) && $POINTER == "$(pki_active_rollover_pointer)" && $ROOT_DIR == "$(pki_root_authority_dir "${PKI_RECORD[candidate_root]}")" && $INT_DIR == "$(pki_intermediate_authority_dir "${PKI_RECORD[candidate_intermediate]}")" && $ROOT_RESERVATION == "$(pki_generation_reservation "${PKI_RECORD[candidate_root]}")" && $INT_RESERVATION == "$(pki_generation_reservation "${PKI_RECORD[candidate_intermediate]}")" ]] || pki_die 'Preparation recovery paths are outside the journal contract'
  if [[ ${PKI_RECORD[transaction_tree_manifest]} != none ]]; then manifest_sequence=${PKI_RECORD[transaction_tree_manifest]##*.}; [[ $manifest_sequence =~ ^[1-9][0-9]*$ && ${PKI_RECORD[transaction_tree_manifest]} == "$(dirname -- "$TXN_DIR")/.$TRANSACTION.transaction-tree.$manifest_sequence" ]] || pki_die 'Preparation transaction manifest path is outside the journal contract'; fi
  if [[ ${PKI_RECORD[transaction_tree_manifest_pending]} != none ]]; then
    pending=${PKI_RECORD[transaction_tree_manifest_pending]}; pending_destination=${PKI_RECORD[transaction_tree_manifest_pending_destination]}
    pending_sequence=${pending_destination##*.}
    [[ $pending_sequence =~ ^[1-9][0-9]*$ && $pending == "$(dirname -- "$TXN_DIR")/.$TRANSACTION.transaction-tree.$pending_sequence" && $pending_destination == "$pending" ]] || pki_die 'Pending transaction manifest paths are outside the journal contract'
    pki_require_file_identity "$pending" "${PKI_RECORD[transaction_tree_manifest_pending_identity]}" 'Pending transaction manifest'
    PKI_RECORD[transaction_tree_manifest]=$pending_destination; PKI_RECORD[transaction_tree_manifest_identity]=${PKI_RECORD[transaction_tree_manifest_pending_identity]}; PKI_RECORD[transaction_tree_manifest_sha256]=${PKI_RECORD[transaction_tree_manifest_pending_sha256]}; PKI_RECORD[transaction_tree_manifest_sequence]=${pending_destination##*.}; PKI_RECORD[transaction_tree_manifest_pending]=none; PKI_RECORD[transaction_tree_manifest_pending_destination]=none; PKI_RECORD[transaction_tree_manifest_pending_identity]=none; PKI_RECORD[transaction_tree_manifest_pending_sha256]=none
    write_loaded_journal "${PKI_RECORD[phase]}" "${PKI_RECORD[committed]}"
  fi
  if [[ ${PKI_RECORD[committed]} == true ]]; then
    ACTIVE_MANIFEST=${PKI_RECORD[active_manifest]}; ACTIVE_IDENTITY=${PKI_RECORD[active_identity]}; POINTER_IDENTITY=${PKI_RECORD[pointer_identity]}; LONG_IDENTITY=${PKI_RECORD[long_identity]}
    [[ ${PKI_RECORD[terminal_outcome]} =~ ^(resumed|rolled-back)$ ]] || pki_die 'Committed preparation journal has no terminal outcome'
    pki_require_file_identity "$ACTIVE_MANIFEST" "$ACTIVE_IDENTITY" 'Active issuer manifest'
    if [[ ${PKI_RECORD[terminal_outcome]} == resumed ]]; then
      pki_require_file_identity "$POINTER" "$POINTER_IDENTITY" 'Active rollover pointer'
      [[ -d $LONG_DIR && ! -L $LONG_DIR && $(pki_dir_identity "$LONG_DIR") == "$LONG_IDENTITY" ]] || pki_die 'Prepared rollover state identity changed'
      pki_validate_tree_manifest "$LONG_DIR" "$LONG_DIR/tree.manifest" "${PKI_RECORD[long_tree_manifest_identity]}" "${PKI_RECORD[long_tree_manifest_sha256]}" tree.manifest
      pki_validate_tree_manifest "$INT_DIR" "$LONG_DIR/candidate-intermediate-tree.manifest" "${PKI_RECORD[candidate_intermediate_tree_manifest_identity]}" "${PKI_RECORD[candidate_intermediate_tree_manifest_sha256]}"
      if [[ $TYPE == root ]]; then pki_validate_tree_manifest "$ROOT_DIR" "$LONG_DIR/candidate-root-tree.manifest" "${PKI_RECORD[candidate_root_tree_manifest_identity]}" "${PKI_RECORD[candidate_root_tree_manifest_sha256]}"; fi
    else
      pki_require_file_identity "$POINTER" absent 'Active rollover pointer'
      [[ ! -e $LONG_DIR && ! -L $LONG_DIR ]] || pki_die 'Rolled-back preparation retained rollover state'
      if [[ $TYPE == root ]]; then [[ ! -e $ROOT_DIR && ! -L $ROOT_DIR ]] || pki_die 'Rolled-back preparation retained a candidate root'
      else [[ $ROOT_DIR == "$(pki_root_authority_dir "${PKI_RECORD[active_root]}")" && -d $ROOT_DIR && ! -L $ROOT_DIR && $(pki_dir_identity "$ROOT_DIR") == "${PKI_RECORD[candidate_root_identity]}" ]] || pki_die 'Active root changed during rolled-back preparation cleanup'; fi
      [[ ! -e $INT_DIR && ! -L $INT_DIR ]] || pki_die 'Rolled-back preparation retained a candidate intermediate'
      pki_require_file_identity "${PKI_RECORD[backup_session]}" "${PKI_RECORD[backup_session_original_identity]}" 'Preparation backup session'
      pki_require_file_identity "$INT_RESERVATION" "${PKI_RECORD[intermediate_reservation_abandoned_identity]}" 'Abandoned intermediate reservation'
      if [[ $TYPE == root ]]; then pki_require_file_identity "$ROOT_RESERVATION" "${PKI_RECORD[root_reservation_abandoned_identity]}" 'Abandoned root reservation'; fi
    fi
    finish_recovered_preparation "${PKI_RECORD[terminal_outcome]}"; pki_ok "Completed terminal cleanup for $TRANSACTION"; exit 0
  fi
  pki_require_file_identity "${PKI_RECORD[active_manifest]}" "${PKI_RECORD[active_identity]}" 'Active issuer manifest'; pki_read_pair_manifest "${PKI_RECORD[active_manifest]}" 'Active issuer'; [[ $ACTIVE_ROOT_ID == "${PKI_RECORD[active_root]}" && $ACTIVE_INTERMEDIATE_ID == "${PKI_RECORD[active_intermediate]}" ]] || pki_die 'Active issuer changed during preparation recovery'
  pki_require_file_identity "${PKI_RECORD[backup_receipt]}" "${PKI_RECORD[receipt_identity]}" 'Preparation backup receipt'
  if [[ ${PKI_RECORD[transaction_identity]} == none ]]; then
    [[ $ACTION == rollback ]] || pki_die 'Planned preparation can only be rolled back before transaction staging'
    if [[ -d $TXN_DIR && ! -L $TXN_DIR && ${PKI_RECORD[recovery_step]} == transaction-dir-pending ]]; then
      [[ $(stat -c '%u:%a' "$TXN_DIR") == "$(id -u):700" && -z $(find "$TXN_DIR" -mindepth 1 -print -quit) ]] || pki_die 'Pending preparation transaction directory is not safely empty'
      PKI_RECORD[transaction_identity]=$(pki_dir_identity "$TXN_DIR")
    else [[ ! -e $TXN_DIR && ! -L $TXN_DIR ]] || pki_die 'Planned preparation transaction path is ambiguous'; fi
    [[ ! -e $ROOT_DIR || $TYPE == intermediate && $ROOT_DIR == "$(pki_root_authority_dir "$ACTIVE_ROOT_ID")" ]] || pki_die 'Unjournaled candidate root state exists'
    [[ ! -e $INT_DIR && ! -e $LONG_DIR && ! -e $POINTER ]] || pki_die 'Unjournaled preparation state exists'
    finish_recovered_preparation rolled-back; pki_ok "Rolled back planned preparation transaction: $TRANSACTION"; exit 0
  fi
  [[ -d $TXN_DIR && ! -L $TXN_DIR && $(pki_dir_identity "$TXN_DIR") == "${PKI_RECORD[transaction_identity]}" ]] || pki_die 'Preparation transaction directory is missing or replaced'
  file_state_allowed "${PKI_RECORD[backup_session]}" 'Preparation backup session' "${PKI_RECORD[backup_session_original_identity]}" "${PKI_RECORD[backup_session_identity]}"
  path=$INT_RESERVATION; kind=intermediate; reserved=${PKI_RECORD[intermediate_reservation_reserved_identity]}; consumed=${PKI_RECORD[intermediate_reservation_consumed_identity]}; abandoned=${PKI_RECORD[intermediate_reservation_abandoned_identity]}; file_state_allowed "$path" "$kind reservation" absent "$reserved" "$consumed" "$abandoned"; if [[ $(pki_file_identity_or_absent "$path") != "$abandoned" ]]; then [[ $abandoned != absent ]] || pki_die 'Intermediate reservation lacks rollback evidence'; pki_require_file_identity "$TXN_DIR/$kind-abandoned" "$abandoned" "$kind abandoned reservation stage"; fi
  if [[ $TYPE == root ]]; then path=$ROOT_RESERVATION; reserved=${PKI_RECORD[root_reservation_reserved_identity]}; consumed=${PKI_RECORD[root_reservation_consumed_identity]}; abandoned=${PKI_RECORD[root_reservation_abandoned_identity]}; file_state_allowed "$path" 'root reservation' absent "$reserved" "$consumed" "$abandoned"; if [[ $(pki_file_identity_or_absent "$path") != "$abandoned" ]]; then [[ $abandoned != absent ]] || pki_die 'Root reservation lacks rollback evidence'; pki_require_file_identity "$TXN_DIR/root-abandoned" "$abandoned" 'Root abandoned reservation stage'; fi; fi
  if [[ ${PKI_RECORD[candidate_intermediate_identity]} == none ]]; then
    [[ $ACTION == rollback ]] || pki_die 'Preparation interrupted before candidate staging completed; recover with rollback'
    [[ ! -e $INT_DIR && ! -L $INT_DIR && ! -e $LONG_DIR && ! -L $LONG_DIR && ! -e $POINTER && ! -L $POINTER ]] || pki_die 'Unjournaled preparation publication exists'
    [[ $TYPE == intermediate || ! -e $ROOT_DIR && ! -L $ROOT_DIR ]] || pki_die 'Unjournaled candidate root exists'
    if [[ ${PKI_RECORD[intermediate_reservation_abandoned_identity]} != absent && $(pki_file_identity_or_absent "$INT_RESERVATION") != "${PKI_RECORD[intermediate_reservation_abandoned_identity]}" ]]; then checkpoint_recovery rollback-reservation-intermediate-pending; pki_publish_staged_file "$TXN_DIR/intermediate-abandoned" "$INT_RESERVATION"; checkpoint_recovery rollback-reservation-intermediate-done; fi
    if [[ $TYPE == root && ${PKI_RECORD[root_reservation_abandoned_identity]} != absent && $(pki_file_identity_or_absent "$ROOT_RESERVATION") != "${PKI_RECORD[root_reservation_abandoned_identity]}" ]]; then checkpoint_recovery rollback-reservation-root-pending; pki_publish_staged_file "$TXN_DIR/root-abandoned" "$ROOT_RESERVATION"; checkpoint_recovery rollback-reservation-root-done; fi
    current=$(pki_file_identity_or_absent "${PKI_RECORD[backup_session]}"); if [[ ${PKI_RECORD[backup_session_identity]} != absent && $current == "${PKI_RECORD[backup_session_identity]}" ]]; then checkpoint_recovery rollback-backup-session-pending; pki_remove_identity_file "${PKI_RECORD[backup_session]}" "$current" || pki_die 'Cannot restore preparation backup session marker'; checkpoint_recovery rollback-backup-session-done; fi
    finish_recovered_preparation rolled-back; pki_ok "Rolled back incomplete preparation transaction: $TRANSACTION"; exit 0
  fi
  STAGE_ROOT="$STAGE_DIR/root"; STAGE_INT="$STAGE_DIR/intermediate"
  INT_REMOVED_ALLOWED=false; ROOT_REMOVED_ALLOWED=false; STATE_REMOVED_ALLOWED=false
  if [[ $ACTION == rollback && ${PKI_RECORD[recovery_action]} == rollback ]]; then
    case ${PKI_RECORD[recovery_step]} in rollback-intermediate-*|rollback-root-*|rollback-state-*|rollback-stage-*|rollback-reservation-*|rollback-backup-session-*|terminal-*) INT_REMOVED_ALLOWED=true ;; esac
    case ${PKI_RECORD[recovery_step]} in rollback-root-*|rollback-state-*|rollback-stage-*|rollback-reservation-*|rollback-backup-session-*|terminal-*) ROOT_REMOVED_ALLOWED=true ;; esac
    case ${PKI_RECORD[recovery_step]} in rollback-state-*|rollback-stage-*|rollback-reservation-*|rollback-backup-session-*|terminal-*) STATE_REMOVED_ALLOWED=true ;; esac
  fi
  [[ ! -e $STAGE_DIR && ! -L $STAGE_DIR || -d $STAGE_DIR && ! -L $STAGE_DIR && $(pki_dir_identity "$STAGE_DIR") == "${PKI_RECORD[stage_identity]}" ]] || pki_die 'Preparation staging directory identity changed'
  if [[ $TYPE == root ]]; then [[ -d $STAGE_ROOT && ! -L $STAGE_ROOT && $(pki_dir_identity "$STAGE_ROOT") == "${PKI_RECORD[candidate_root_identity]}" && ! -e $ROOT_DIR || -d $ROOT_DIR && ! -L $ROOT_DIR && $(pki_dir_identity "$ROOT_DIR") == "${PKI_RECORD[candidate_root_identity]}" && ! -e $STAGE_ROOT || ! -e $STAGE_ROOT && ! -e $ROOT_DIR && $ROOT_REMOVED_ALLOWED == true ]] || pki_die 'Candidate root location is ambiguous or replaced'
  else [[ -d $ROOT_DIR && ! -L $ROOT_DIR && $(pki_dir_identity "$ROOT_DIR") == "${PKI_RECORD[candidate_root_identity]}" ]] || pki_die 'Active root identity changed'; fi
  [[ -d $STAGE_INT && ! -L $STAGE_INT && $(pki_dir_identity "$STAGE_INT") == "${PKI_RECORD[candidate_intermediate_identity]}" && ! -e $INT_DIR || -d $INT_DIR && ! -L $INT_DIR && $(pki_dir_identity "$INT_DIR") == "${PKI_RECORD[candidate_intermediate_identity]}" && ! -e $STAGE_INT || ! -e $STAGE_INT && ! -e $INT_DIR && $INT_REMOVED_ALLOWED == true ]] || pki_die 'Candidate intermediate location is ambiguous or replaced'
  ROOT_LOCATION=$ROOT_DIR; [[ $TYPE != root || -d $ROOT_LOCATION ]] || ROOT_LOCATION=$STAGE_ROOT; INT_LOCATION=$INT_DIR; [[ -d $INT_LOCATION ]] || INT_LOCATION=$STAGE_INT
  if [[ -d $ROOT_LOCATION ]]; then pki_require_file_identity "$ROOT_LOCATION/private/root-ca.key" "${PKI_RECORD[candidate_root_key_identity]}" 'Candidate root key'; verify_bound_file "$ROOT_LOCATION/certs/root-ca.crt" "${PKI_RECORD[candidate_root_cert_identity]}" "${PKI_RECORD[candidate_root_cert_sha256]}" 'Candidate root certificate'; fi
  if [[ -d $INT_LOCATION ]]; then pki_require_file_identity "$INT_LOCATION/private/intermediate-ca.key" "${PKI_RECORD[candidate_intermediate_key_identity]}" 'Candidate intermediate key'; verify_bound_file "$INT_LOCATION/certs/intermediate-ca.crt" "${PKI_RECORD[candidate_intermediate_cert_identity]}" "${PKI_RECORD[candidate_intermediate_cert_sha256]}" 'Candidate intermediate certificate'; verify_bound_file "$INT_LOCATION/certs/ca-chain.crt" "${PKI_RECORD[candidate_chain_identity]}" "${PKI_RECORD[candidate_chain_sha256]}" 'Candidate CA chain'; fi
  [[ -d $LONG_STAGE && ! -L $LONG_STAGE && $(pki_dir_identity "$LONG_STAGE") == "${PKI_RECORD[long_identity]}" && ! -e $LONG_DIR || -d $LONG_DIR && ! -L $LONG_DIR && $(pki_dir_identity "$LONG_DIR") == "${PKI_RECORD[long_identity]}" && ! -e $LONG_STAGE || ! -e $LONG_STAGE && ! -e $LONG_DIR && $STATE_REMOVED_ALLOWED == true ]] || pki_die 'Long-lived rollover state is ambiguous or replaced'
  if [[ -d $LONG_STAGE ]]; then STATE_LOCATION=$LONG_STAGE; else STATE_LOCATION=$LONG_DIR; fi
  if [[ -d ${STATE_LOCATION:-} ]]; then
    verify_bound_file "$STATE_LOCATION/manifest" "${PKI_RECORD[long_manifest_identity]}" "${PKI_RECORD[long_manifest_sha256]}" 'Rollover manifest'
    pki_validate_tree_manifest "$STATE_LOCATION" "$STATE_LOCATION/tree.manifest" "${PKI_RECORD[long_tree_manifest_identity]}" "${PKI_RECORD[long_tree_manifest_sha256]}" tree.manifest
    if [[ $TYPE == root ]]; then pki_require_file_identity "$STATE_LOCATION/trust-consumers.yml" "${PKI_RECORD[trust_snapshot_identity]}" 'Trust consumer snapshot'; value=$(sha256sum "$STATE_LOCATION/trust-consumers.yml"); [[ ${value%% *} == "${PKI_RECORD[trust_snapshot_sha256]}" ]] || pki_die 'Trust consumer snapshot digest changed'; fi
    if [[ $TYPE == root && -d $ROOT_LOCATION ]]; then pki_validate_tree_manifest "$ROOT_LOCATION" "$STATE_LOCATION/candidate-root-tree.manifest" "${PKI_RECORD[candidate_root_tree_manifest_identity]}" "${PKI_RECORD[candidate_root_tree_manifest_sha256]}"; fi
    if [[ -d $INT_LOCATION ]]; then pki_validate_tree_manifest "$INT_LOCATION" "$STATE_LOCATION/candidate-intermediate-tree.manifest" "${PKI_RECORD[candidate_intermediate_tree_manifest_identity]}" "${PKI_RECORD[candidate_intermediate_tree_manifest_sha256]}"; fi
  fi
  file_state_allowed "$POINTER" 'Active rollover pointer' absent "${PKI_RECORD[pointer_identity]}"
  ROOT_DB_KEYS=(index index_attr serial crlnumber index_old index_attr_old serial_old crlnumber_old newcert); declare -A ROOT_DB_PATH=() ROOT_DB_BACKUP=()
  if [[ $TYPE == intermediate ]]; then
    ROOT_CA_DIR=$ROOT_DIR; issued=${PKI_RECORD[issued_serial]}; backup="$STAGE_DIR/root-backup"; ROOT_DB_PATH[index]="$ROOT_CA_DIR/index.txt"; ROOT_DB_PATH[index_attr]="$ROOT_CA_DIR/index.txt.attr"; ROOT_DB_PATH[serial]="$ROOT_CA_DIR/serial"; ROOT_DB_PATH[crlnumber]="$ROOT_CA_DIR/crlnumber"; ROOT_DB_PATH[index_old]="$ROOT_CA_DIR/index.txt.old"; ROOT_DB_PATH[index_attr_old]="$ROOT_CA_DIR/index.txt.attr.old"; ROOT_DB_PATH[serial_old]="$ROOT_CA_DIR/serial.old"; ROOT_DB_PATH[crlnumber_old]="$ROOT_CA_DIR/crlnumber.old"; ROOT_DB_PATH[newcert]="$ROOT_CA_DIR/newcerts/$issued.pem"; ROOT_DB_BACKUP[index]="$backup/index.txt"; ROOT_DB_BACKUP[index_attr]="$backup/index.txt.attr"; ROOT_DB_BACKUP[serial]="$backup/serial"; ROOT_DB_BACKUP[crlnumber]="$backup/crlnumber"; ROOT_DB_BACKUP[index_old]="$backup/index.txt.old"; ROOT_DB_BACKUP[index_attr_old]="$backup/index.txt.attr.old"; ROOT_DB_BACKUP[serial_old]="$backup/serial.old"; ROOT_DB_BACKUP[crlnumber_old]="$backup/crlnumber.old"; ROOT_DB_BACKUP[newcert]=none
    for key in "${ROOT_DB_KEYS[@]}"; do
      [[ -v PKI_RECORD[root_${key}_source_identity] ]] || pki_die "Preparation recovery journal is missing root $key source identity"
      file_state_allowed "${ROOT_DB_PATH[$key]}" "Root $key" "${PKI_RECORD[root_${key}_pre_identity]}" "${PKI_RECORD[root_${key}_post_identity]}" "${PKI_RECORD[root_${key}_rollback_identity]}"
      current=$(pki_file_identity_or_absent_full "${ROOT_DB_PATH[$key]}")
      if [[ $current == "${PKI_RECORD[root_${key}_post_identity]}" && ${PKI_RECORD[root_${key}_pre_identity]} != absent ]]; then pki_require_file_identity "${ROOT_DB_BACKUP[$key]}" "${PKI_RECORD[root_${key}_backup_identity]}" "Root $key rollback copy"; fi
      if [[ $current == "${PKI_RECORD[root_${key}_pre_identity]}" && ${PKI_RECORD[root_${key}_source_identity]} != absent ]]; then file=${ROOT_DB_PATH[$key]#"$ROOT_CA_DIR/"}; pki_require_file_identity "$STAGE_ROOT/$file" "${PKI_RECORD[root_${key}_source_identity]}" "Staged root $key publication source"; fi
    done
    if [[ -d ${PKI_RECORD[root_stage]} ]]; then [[ $(pki_dir_identity "${PKI_RECORD[root_stage]}") == "${PKI_RECORD[root_stage_identity]}" ]] || pki_die 'Sensitive root stage identity changed'; pki_require_file_identity "${PKI_RECORD[root_stage]}/private/root-ca.key" "${PKI_RECORD[root_stage_key_identity]}" 'Copied root signing key'; fi
  fi
  PKI_RECORD[recovery_action]=$ACTION
  if [[ $ACTION == rollback ]]; then
    current=$(pki_file_identity_or_absent "$POINTER"); if [[ $current == "${PKI_RECORD[pointer_identity]}" ]]; then checkpoint_recovery rollback-pointer-pending; pki_remove_identity_file "$POINTER" "$current" || pki_die 'Cannot remove active rollover pointer'; checkpoint_recovery rollback-pointer-done; fi
    if [[ $TYPE == intermediate ]]; then for key in "${ROOT_DB_KEYS[@]}"; do current=$(pki_file_identity_or_absent_full "${ROOT_DB_PATH[$key]}"); if [[ $current == "${PKI_RECORD[root_${key}_post_identity]}" && ${PKI_RECORD[root_${key}_pre_identity]} != "${PKI_RECORD[root_${key}_post_identity]}" ]]; then checkpoint_recovery "rollback-root-db-$key-pending"; pki_restore_journaled_file_exact "${ROOT_DB_PATH[$key]}" "${PKI_RECORD[root_${key}_pre_identity]}" "${PKI_RECORD[root_${key}_post_identity]}" "${ROOT_DB_BACKUP[$key]}" "${PKI_RECORD[root_${key}_backup_identity]}" "Root $key"; if [[ ${PKI_RECORD[root_${key}_pre_identity]} != absent ]]; then PKI_RECORD[root_${key}_rollback_identity]=$PKI_PUBLISHED_FILE_IDENTITY; fi; checkpoint_recovery "rollback-root-db-$key-done"; fi; done; fi
    if [[ -d $INT_DIR ]]; then checkpoint_recovery rollback-intermediate-pending; pki_remove_manifested_tree "$INT_DIR" "${PKI_RECORD[candidate_intermediate_identity]}" "$(dirname -- "$INT_DIR")" "$STATE_LOCATION/candidate-intermediate-tree.manifest" "${PKI_RECORD[candidate_intermediate_tree_manifest_identity]}" "${PKI_RECORD[candidate_intermediate_tree_manifest_sha256]}" || pki_die 'Cannot remove candidate intermediate'; checkpoint_recovery rollback-intermediate-done; fi
    if [[ $TYPE == root && -d $ROOT_DIR ]]; then checkpoint_recovery rollback-root-pending; pki_remove_manifested_tree "$ROOT_DIR" "${PKI_RECORD[candidate_root_identity]}" "$(dirname -- "$ROOT_DIR")" "$STATE_LOCATION/candidate-root-tree.manifest" "${PKI_RECORD[candidate_root_tree_manifest_identity]}" "${PKI_RECORD[candidate_root_tree_manifest_sha256]}" || pki_die 'Cannot remove candidate root'; checkpoint_recovery rollback-root-done; fi
    if [[ -d $LONG_DIR ]]; then checkpoint_recovery rollback-state-pending; pki_remove_manifested_tree "$LONG_DIR" "${PKI_RECORD[long_identity]}" "$(dirname -- "$LONG_DIR")" "$LONG_DIR/tree.manifest" "${PKI_RECORD[long_tree_manifest_identity]}" "${PKI_RECORD[long_tree_manifest_sha256]}" tree.manifest || pki_die 'Cannot remove long-lived rollover state'; checkpoint_recovery rollback-state-done; elif [[ -d $LONG_STAGE ]]; then checkpoint_recovery rollback-state-pending; pki_remove_manifested_tree "$LONG_STAGE" "${PKI_RECORD[long_identity]}" "$TXN_DIR" "$LONG_STAGE/tree.manifest" "${PKI_RECORD[long_tree_manifest_identity]}" "${PKI_RECORD[long_tree_manifest_sha256]}" tree.manifest || pki_die 'Cannot remove staged rollover state'; checkpoint_recovery rollback-state-done; fi
    if [[ -d $STAGE_DIR ]]; then checkpoint_recovery rollback-stage-pending; pki_remove_manifested_tree "$STAGE_DIR" "${PKI_RECORD[stage_identity]}" "$TXN_DIR" "${PKI_RECORD[stage_tree_manifest]}" "${PKI_RECORD[stage_tree_manifest_identity]}" "${PKI_RECORD[stage_tree_manifest_sha256]}" || pki_die 'Cannot remove preparation staging'; checkpoint_recovery rollback-stage-done; fi
    path=$INT_RESERVATION; kind=intermediate; abandoned=${PKI_RECORD[intermediate_reservation_abandoned_identity]}; if [[ $(pki_file_identity_or_absent "$path") != "$abandoned" ]]; then checkpoint_recovery "rollback-reservation-$kind-pending"; pki_publish_staged_file "$TXN_DIR/$kind-abandoned" "$path"; checkpoint_recovery "rollback-reservation-$kind-done"; fi
    if [[ $TYPE == root && $(pki_file_identity_or_absent "$ROOT_RESERVATION") != "${PKI_RECORD[root_reservation_abandoned_identity]}" ]]; then checkpoint_recovery rollback-reservation-root-pending; pki_publish_staged_file "$TXN_DIR/root-abandoned" "$ROOT_RESERVATION"; checkpoint_recovery rollback-reservation-root-done; fi
    current=$(pki_file_identity_or_absent "${PKI_RECORD[backup_session]}"); if [[ $current == "${PKI_RECORD[backup_session_identity]}" ]]; then checkpoint_recovery rollback-backup-session-pending; pki_remove_identity_file "${PKI_RECORD[backup_session]}" "$current" || pki_die 'Cannot restore preparation backup session marker'; checkpoint_recovery rollback-backup-session-done; fi
    finish_recovered_preparation rolled-back; pki_ok "Rolled back preparation transaction: $TRANSACTION"; exit 0
  fi
  [[ ${PKI_RECORD[candidate_intermediate_identity]} != none ]] || pki_die 'Preparation cannot resume before candidate staging completed'
  current=$(pki_file_identity_or_absent "${PKI_RECORD[backup_session]}"); if [[ $current == absent ]]; then checkpoint_recovery resume-backup-session-pending; pki_publish_staged_file "$TXN_DIR/backup-session.publish" "${PKI_RECORD[backup_session]}"; checkpoint_recovery resume-backup-session-done; fi
  if [[ $TYPE == root && $(pki_file_identity_or_absent "$ROOT_RESERVATION") == absent ]]; then checkpoint_recovery resume-reserve-root-pending; pki_publish_staged_file "$TXN_DIR/root-reserved" "$ROOT_RESERVATION"; checkpoint_recovery resume-reserve-root-done; fi
  if [[ $(pki_file_identity_or_absent "$INT_RESERVATION") == absent ]]; then checkpoint_recovery resume-reserve-intermediate-pending; pki_publish_staged_file "$TXN_DIR/intermediate-reserved" "$INT_RESERVATION"; checkpoint_recovery resume-reserve-intermediate-done; fi
  if [[ $TYPE == root && -d $STAGE_ROOT ]]; then checkpoint_recovery resume-publish-root-pending; mv --no-copy --update=none-fail -T -- "$STAGE_ROOT" "$ROOT_DIR"; pki_fsync_rename_parents "$STAGE_DIR" "$(dirname -- "$ROOT_DIR")"; checkpoint_recovery resume-publish-root-done; fi
  if [[ -d $STAGE_INT ]]; then checkpoint_recovery resume-publish-intermediate-pending; mv --no-copy --update=none-fail -T -- "$STAGE_INT" "$INT_DIR"; pki_fsync_rename_parents "$STAGE_DIR" "$(dirname -- "$INT_DIR")"; checkpoint_recovery resume-publish-intermediate-done; fi
  if [[ $TYPE == intermediate ]]; then for key in "${ROOT_DB_KEYS[@]}"; do current=$(pki_file_identity_or_absent_full "${ROOT_DB_PATH[$key]}"); if [[ $current == "${PKI_RECORD[root_${key}_pre_identity]}" && ${PKI_RECORD[root_${key}_pre_identity]} != "${PKI_RECORD[root_${key}_post_identity]}" ]]; then file=${ROOT_DB_PATH[$key]#"$ROOT_CA_DIR/"}; checkpoint_recovery "resume-root-db-$key-pending"; pki_require_file_identity "$STAGE_ROOT/$file" "${PKI_RECORD[root_${key}_source_identity]}" "Staged root $key publication source"; pki_publish_staged_file_exact "$STAGE_ROOT/$file" "${ROOT_DB_PATH[$key]}"; PKI_RECORD[root_${key}_post_identity]=$PKI_PUBLISHED_FILE_IDENTITY; checkpoint_recovery "resume-root-db-$key-done"; fi; done; fi
  if [[ $TYPE == root && $(pki_file_identity_or_absent "$ROOT_RESERVATION") == "${PKI_RECORD[root_reservation_reserved_identity]}" ]]; then checkpoint_recovery resume-consume-root-pending; pki_publish_staged_file "$TXN_DIR/root-consumed" "$ROOT_RESERVATION"; checkpoint_recovery resume-consume-root-done; fi
  if [[ $(pki_file_identity_or_absent "$INT_RESERVATION") == "${PKI_RECORD[intermediate_reservation_reserved_identity]}" ]]; then checkpoint_recovery resume-consume-intermediate-pending; pki_publish_staged_file "$TXN_DIR/intermediate-consumed" "$INT_RESERVATION"; checkpoint_recovery resume-consume-intermediate-done; fi
  if [[ $TYPE == intermediate && -d ${PKI_RECORD[root_stage]} ]]; then checkpoint_recovery resume-cleanup-root-stage-pending; pki_remove_manifested_tree "${PKI_RECORD[root_stage]}" "${PKI_RECORD[root_stage_identity]}" "$STAGE_DIR" "$STATE_LOCATION/root-signing-stage-tree.manifest" "${PKI_RECORD[root_stage_tree_manifest_identity]}" "${PKI_RECORD[root_stage_tree_manifest_sha256]}" || pki_die 'Cannot remove copied root signing stage'; checkpoint_recovery resume-cleanup-root-stage-done; fi
  if [[ -d $LONG_STAGE ]]; then checkpoint_recovery resume-publish-state-pending; mv --no-copy --update=none-fail -T -- "$LONG_STAGE" "$LONG_DIR"; pki_fsync_rename_parents "$TXN_DIR" "$(dirname -- "$LONG_DIR")"; checkpoint_recovery resume-publish-state-done; fi
  if [[ $(pki_file_identity_or_absent "$POINTER") == absent ]]; then checkpoint_recovery resume-publish-pointer-pending; pki_publish_staged_file "$TXN_DIR/active-rollover.publish" "$POINTER"; checkpoint_recovery resume-publish-pointer-done; fi
  finish_recovered_preparation resumed; pki_ok "Resumed preparation transaction: $TRANSACTION"; exit 0
fi
if [[ ${PKI_RECORD[operation]:-} == root-bootstrap || ${PKI_RECORD[operation]:-} == intermediate-bootstrap ]]; then
  if [[ ${PKI_RECORD[operation]} == root-bootstrap ]]; then [[ $ACTION == rollback ]] || pki_die 'Root bootstrap recovery supports only rollback'
  elif [[ $ACTION == resume ]]; then [[ ${PKI_RECORD[phase]} == cleanup-* || ${PKI_RECORD[recovery_step]:-} == cleanup-* ]] || pki_die 'Intermediate bootstrap resume is limited to sensitive-stage cleanup'
  else [[ $ACTION == rollback ]] || pki_die 'Intermediate bootstrap recovery action is invalid'; fi
  for field in schema operation transaction phase stage_dir stage_identity transaction_dir transaction_identity reservation reservation_reserved_identity reservation_consumed_identity reservation_abandoned_identity recovery_action recovery_step committed; do [[ -v PKI_RECORD[$field] ]] || pki_die "Bootstrap recovery journal is missing field: $field"; done
  [[ ${PKI_RECORD[schema]} == 3 ]] || pki_die 'Bootstrap recovery journal schema is unsupported'
  TXN_DIR=${PKI_RECORD[transaction_dir]}; [[ $TXN_DIR == "$PKI_DIR/state/rollover/$TRANSACTION" && -d $TXN_DIR && ! -L $TXN_DIR && $(pki_dir_identity "$TXN_DIR") == "${PKI_RECORD[transaction_identity]}" ]] || pki_die 'Bootstrap recovery transaction directory is missing, replaced, or unsafe'
  stage=${PKI_RECORD[stage_dir]}; stage_identity=${PKI_RECORD[stage_identity]}; reservation=${PKI_RECORD[reservation]}; abandoned_stage="$TXN_DIR/reservation-abandoned"
  file_state_allowed "$reservation" 'Bootstrap reservation' absent "${PKI_RECORD[reservation_reserved_identity]}" "${PKI_RECORD[reservation_consumed_identity]}" "${PKI_RECORD[reservation_abandoned_identity]}"
  [[ $(pki_file_identity_or_absent "$reservation") == "${PKI_RECORD[reservation_abandoned_identity]}" ]] || pki_require_file_identity "$abandoned_stage" "${PKI_RECORD[reservation_abandoned_identity]}" 'Abandoned bootstrap reservation stage'
  [[ $stage == none || ! -e $stage && ! -L $stage || -d $stage && ! -L $stage && $(pki_dir_identity "$stage") == "$stage_identity" ]] || pki_die 'Bootstrap staging identity changed'
  PKI_RECORD[recovery_action]=rollback
  if [[ ${PKI_RECORD[operation]} == root-bootstrap ]]; then
    for field in generation authority_dir authority_identity bootstrap_identity; do [[ -v PKI_RECORD[$field] ]] || pki_die "Root bootstrap recovery journal is missing field: $field"; done
    generation=${PKI_RECORD[generation]}; pki_validate_root_generation "$generation"; authority=${PKI_RECORD[authority_dir]}; authority_identity=${PKI_RECORD[authority_identity]}
    [[ $authority == "$(pki_root_authority_dir "$generation")" && $reservation == "$(pki_generation_reservation "$generation")" ]] || pki_die 'Root bootstrap recovery paths are invalid'
    [[ ! -e $authority && ! -L $authority || -d $authority && ! -L $authority && $authority_identity != none && $(pki_dir_identity "$authority") == "$authority_identity" ]] || pki_die 'Root bootstrap authority identity changed'
    bootstrap=$(pki_bootstrap_root_manifest); file_state_allowed "$bootstrap" 'Bootstrap root manifest' absent "${PKI_RECORD[bootstrap_identity]}"
    if [[ $(pki_file_identity_or_absent "$bootstrap") != absent ]]; then checkpoint_recovery rollback-bootstrap-pending; pki_remove_identity_file "$bootstrap" "${PKI_RECORD[bootstrap_identity]}" || pki_die 'Cannot remove bootstrap root manifest'; checkpoint_recovery rollback-bootstrap-done; fi
  else
    for field in root_generation intermediate_generation root_dir intermediate_dir intermediate_identity issued_serial bootstrap_fingerprint active_identity bootstrap_identity bootstrap_rollback_identity root_mutated root_stage root_stage_identity; do [[ -v PKI_RECORD[$field] ]] || pki_die "Intermediate recovery journal is missing field: $field"; done
    root_generation=${PKI_RECORD[root_generation]}; generation=${PKI_RECORD[intermediate_generation]}; pki_validate_root_generation "$root_generation"; pki_validate_intermediate_generation "$generation"; [[ $generation == "$root_generation"-i* ]] || pki_die 'Intermediate bootstrap generations are mismatched'
    root_dir=${PKI_RECORD[root_dir]}; authority=${PKI_RECORD[intermediate_dir]}; authority_identity=${PKI_RECORD[intermediate_identity]}; issued_serial=${PKI_RECORD[issued_serial]}
    [[ $root_dir == "$(pki_root_authority_dir "$root_generation")" && $authority == "$(pki_intermediate_authority_dir "$generation")" && $reservation == "$(pki_generation_reservation "$generation")" ]] || pki_die 'Intermediate bootstrap recovery paths are invalid'
    root_stage=${PKI_RECORD[root_stage]}; root_stage_identity=${PKI_RECORD[root_stage_identity]}
    if [[ $root_stage != none ]]; then [[ $root_stage == "$stage/root" && $root_stage_identity != none ]] || pki_die 'Sensitive root signing stage path is invalid'; [[ ! -e $root_stage && ! -L $root_stage || -d $root_stage && ! -L $root_stage && $(pki_dir_identity "$root_stage") == "$root_stage_identity" ]] || pki_die 'Sensitive root signing stage identity changed'; fi
    [[ ! -e $authority && ! -L $authority || -d $authority && ! -L $authority && $authority_identity != none && $(pki_dir_identity "$authority") == "$authority_identity" ]] || pki_die 'Intermediate bootstrap authority identity changed'
    active=$(pki_active_issuer_manifest); file_state_allowed "$active" 'Active issuer manifest' absent "${PKI_RECORD[active_identity]}"
    bootstrap=$(pki_bootstrap_root_manifest); bootstrap_stage="$TXN_DIR/bootstrap-rollback"; file_state_allowed "$bootstrap" 'Bootstrap root manifest' absent "${PKI_RECORD[bootstrap_identity]}" "${PKI_RECORD[bootstrap_rollback_identity]}"
    [[ $(pki_file_identity_or_absent "$bootstrap") != absent ]] || pki_require_file_identity "$bootstrap_stage" "${PKI_RECORD[bootstrap_rollback_identity]}" 'Bootstrap rollback stage'
    if [[ ${PKI_RECORD[root_mutated]} == true ]]; then
      declare -A db_path=() db_backup=(); db_keys=(index index_attr serial crlnumber index_old index_attr_old serial_old crlnumber_old newcert)
      db_path[index]="$root_dir/index.txt"; db_path[index_attr]="$root_dir/index.txt.attr"; db_path[serial]="$root_dir/serial"; db_path[crlnumber]="$root_dir/crlnumber"; db_path[index_old]="$root_dir/index.txt.old"; db_path[index_attr_old]="$root_dir/index.txt.attr.old"; db_path[serial_old]="$root_dir/serial.old"; db_path[crlnumber_old]="$root_dir/crlnumber.old"; db_path[newcert]="$root_dir/newcerts/$issued_serial.pem"
      backup="$stage/root-backup"; db_backup[index]="$backup/index.txt"; db_backup[index_attr]="$backup/index.txt.attr"; db_backup[serial]="$backup/serial"; db_backup[crlnumber]="$backup/crlnumber"; db_backup[index_old]="$backup/index.txt.old"; db_backup[index_attr_old]="$backup/index.txt.attr.old"; db_backup[serial_old]="$backup/serial.old"; db_backup[crlnumber_old]="$backup/crlnumber.old"; db_backup[newcert]=none
      for key in "${db_keys[@]}"; do for suffix in pre_identity post_identity backup_identity; do field="root_${key}_${suffix}"; [[ -v PKI_RECORD[$field] ]] || pki_die "Intermediate recovery journal is missing field: $field"; done; file_state_allowed "${db_path[$key]}" "Root $key state" "${PKI_RECORD[root_${key}_pre_identity]}" "${PKI_RECORD[root_${key}_post_identity]}" "${PKI_RECORD[root_${key}_backup_identity]}"; current=$(pki_file_identity_or_absent "${db_path[$key]}"); if [[ $current == "${PKI_RECORD[root_${key}_post_identity]}" && ${PKI_RECORD[root_${key}_pre_identity]} != absent ]]; then pki_require_file_identity "${db_backup[$key]}" "${PKI_RECORD[root_${key}_backup_identity]}" "Root $key rollback copy"; fi; done
    fi
    if [[ $ACTION == resume ]]; then
      [[ -d $authority && ! -L $authority && $(pki_dir_identity "$authority") == "$authority_identity" ]] || pki_die 'Published intermediate authority is not complete'
      pki_require_file_identity "$active" "${PKI_RECORD[active_identity]}" 'Active issuer manifest'; pki_require_file_identity "$bootstrap" absent 'Bootstrap root manifest'; pki_require_file_identity "$reservation" "${PKI_RECORD[reservation_consumed_identity]}" 'Consumed intermediate reservation'
      for key in "${db_keys[@]}"; do pki_require_file_identity "${db_path[$key]}" "${PKI_RECORD[root_${key}_post_identity]}" "Published root $key state"; done
      if [[ $root_stage != none && -d $root_stage ]]; then checkpoint_recovery cleanup-pending; pki_remove_journaled_tree "$root_stage" "$root_stage_identity" "$stage" || pki_die 'Cannot remove sensitive root signing stage'; fi
      checkpoint_recovery cleanup-done; write_loaded_journal complete true; rm -f -- "$MARKER"; pki_fsync "$(dirname -- "$MARKER")"
      [[ $stage == none || ! -d $stage ]] || pki_remove_journaled_tree "$stage" "$stage_identity" "$(dirname -- "$stage")" || pki_die 'Cannot remove intermediate bootstrap staging'
      pki_ok "Completed sensitive-stage cleanup for intermediate bootstrap transaction: $TRANSACTION"; exit 0
    fi
    if [[ $(pki_file_identity_or_absent "$active") != absent ]]; then checkpoint_recovery rollback-active-pending; pki_remove_identity_file "$active" "${PKI_RECORD[active_identity]}" || pki_die 'Cannot remove active issuer manifest'; checkpoint_recovery rollback-active-done; fi
    if [[ $(pki_file_identity_or_absent "$bootstrap") == absent ]]; then checkpoint_recovery rollback-bootstrap-pending; pki_publish_staged_file "$bootstrap_stage" "$bootstrap"; checkpoint_recovery rollback-bootstrap-done; fi
    if [[ ${PKI_RECORD[root_mutated]} == true ]]; then for key in "${db_keys[@]}"; do current=$(pki_file_identity_or_absent "${db_path[$key]}"); if [[ $current == "${PKI_RECORD[root_${key}_post_identity]}" && ${PKI_RECORD[root_${key}_pre_identity]} != "${PKI_RECORD[root_${key}_post_identity]}" ]]; then checkpoint_recovery "rollback-root-$key-pending"; pki_restore_journaled_file "${db_path[$key]}" "${PKI_RECORD[root_${key}_pre_identity]}" "${PKI_RECORD[root_${key}_post_identity]}" "${db_backup[$key]}" "${PKI_RECORD[root_${key}_backup_identity]}" "Root $key" || pki_die "Cannot restore root $key state"; checkpoint_recovery "rollback-root-$key-done"; fi; done; fi
  fi
  if [[ -d $authority ]]; then checkpoint_recovery rollback-authority-pending; pki_remove_journaled_tree "$authority" "$authority_identity" "$(dirname -- "$authority")" || pki_die 'Cannot remove journaled bootstrap authority'; checkpoint_recovery rollback-authority-done; fi
  if [[ $stage != none && -d $stage ]]; then checkpoint_recovery rollback-stage-pending; pki_remove_journaled_tree "$stage" "$stage_identity" "$(dirname -- "$stage")" || pki_die 'Cannot remove journaled bootstrap staging'; checkpoint_recovery rollback-stage-done; fi
  if [[ $(pki_file_identity_or_absent "$reservation") != "${PKI_RECORD[reservation_abandoned_identity]}" ]]; then checkpoint_recovery rollback-reservation-pending; pki_publish_staged_file "$abandoned_stage" "$reservation"; checkpoint_recovery rollback-reservation-done; fi
  PKI_RECORD[reservation_identity]=${PKI_RECORD[reservation_abandoned_identity]}; PKI_RECORD[recovery_step]=complete; write_loaded_journal rolled-back true
  rm -f -- "$MARKER"; pki_fsync "$(dirname -- "$MARKER")"; pki_ok "Rolled back bootstrap transaction: $TRANSACTION"; exit 0
fi
required_fields=(schema operation transaction phase legacy_root legacy_intermediate new_root new_intermediate root_source_identity intermediate_source_identity root_sha256 intermediate_sha256 transaction_dir transaction_identity provenance_stage provenance_dir provenance_identity provenance_manifest provenance_manifest_identity provenance_manifest_sha256 receipt_identity services_identity services_sha256 backup_receipt private_repo backup_session backup_session_original_identity backup_session_published_identity root_reservation root_reservation_original_identity root_reservation_reserved_identity root_reservation_consumed_identity root_reservation_rollback_identity intermediate_reservation intermediate_reservation_original_identity intermediate_reservation_reserved_identity intermediate_reservation_consumed_identity intermediate_reservation_rollback_identity root_config_original_identity root_config_published_identity root_config_rollback_identity root_config_backup_identity intermediate_config_original_identity intermediate_config_published_identity intermediate_config_rollback_identity intermediate_config_backup_identity issuer_ledger issuer_ledger_identity issuer_ledger_sha256 quarantine_ledger quarantine_ledger_identity quarantine_ledger_sha256 active_manifest active_original_identity active_published_identity committed)
for field in "${required_fields[@]}"; do [[ -v PKI_RECORD[$field] ]] || pki_die "Recovery journal is missing field: $field"; done
[[ ${PKI_RECORD[schema]} == 2 && ${PKI_RECORD[operation]} == legacy-migrate && ${PKI_RECORD[transaction]} == "$TRANSACTION" && ${PKI_RECORD[committed]} == false ]] || pki_die 'Recovery journal does not describe the requested uncommitted migration'
LEGACY_ROOT=${PKI_RECORD[legacy_root]}; LEGACY_INT=${PKI_RECORD[legacy_intermediate]}; NEW_ROOT=${PKI_RECORD[new_root]}; NEW_INT=${PKI_RECORD[new_intermediate]}; TXN_DIR=${PKI_RECORD[transaction_dir]}; ROOT_ID=${PKI_RECORD[root_source_identity]}; INT_ID=${PKI_RECORD[intermediate_source_identity]}
ROOT_RESERVATION=${PKI_RECORD[root_reservation]}; INT_RESERVATION=${PKI_RECORD[intermediate_reservation]}; BACKUP_SESSION=${PKI_RECORD[backup_session]}; ACTIVE_MANIFEST=${PKI_RECORD[active_manifest]}; ISSUER_LEDGER=${PKI_RECORD[issuer_ledger]}; QUARANTINE_LEDGER=${PKI_RECORD[quarantine_ledger]}
PROVENANCE_STAGE=${PKI_RECORD[provenance_stage]}; PROVENANCE_DIR=${PKI_RECORD[provenance_dir]}; PROVENANCE_IDENTITY=${PKI_RECORD[provenance_identity]}
[[ $LEGACY_ROOT == "$PKI_DIR/root-ca" && $LEGACY_INT == "$PKI_DIR/intermediate-ca" && $NEW_ROOT == "$PKI_DIR/authorities/roots/g1" && $NEW_INT == "$PKI_DIR/authorities/intermediates/g1-i1" && $TXN_DIR == "$PKI_DIR/state/rollover/$TRANSACTION" && $PROVENANCE_STAGE == "$PKI_DIR/legacy/.$TRANSACTION.publish" && $PROVENANCE_DIR == "$PKI_DIR/legacy/$TRANSACTION" && ${PKI_RECORD[provenance_manifest]} == "$PROVENANCE_STAGE/provenance-manifest" && $ROOT_RESERVATION == "$(pki_generation_reservation g1)" && $INT_RESERVATION == "$(pki_generation_reservation g1-i1)" && $ACTIVE_MANIFEST == "$(pki_active_issuer_manifest)" && $BACKUP_SESSION == "$PKI_DIR/state/rollover/backup-session-"* && $ISSUER_LEDGER == "$TXN_DIR/issuer-identities" && $QUARANTINE_LEDGER == "$TXN_DIR/quarantine-identities" ]] || pki_die 'Recovery journal paths are outside the exact migration contract'
[[ -d $TXN_DIR && ! -L $TXN_DIR && $(stat -c '%u:%a' "$TXN_DIR") == "$(id -u):700" && $(pki_dir_identity "$TXN_DIR") == "${PKI_RECORD[transaction_identity]}" ]] || pki_die 'Recovery transaction directory is missing, replaced, or unsafe'
[[ -d $PROVENANCE_STAGE && ! -L $PROVENANCE_STAGE && $(pki_dir_identity "$PROVENANCE_STAGE") == "$PROVENANCE_IDENTITY" && ! -e $PROVENANCE_DIR && ! -L $PROVENANCE_DIR || -d $PROVENANCE_DIR && ! -L $PROVENANCE_DIR && $(pki_dir_identity "$PROVENANCE_DIR") == "$PROVENANCE_IDENTITY" && ! -e $PROVENANCE_STAGE && ! -L $PROVENANCE_STAGE || ! -e $PROVENANCE_STAGE && ! -L $PROVENANCE_STAGE && ! -e $PROVENANCE_DIR && ! -L $PROVENANCE_DIR && ${PKI_RECORD[recovery_action]:-} == rollback && ${PKI_RECORD[recovery_step]:-} == rollback-provenance-* ]] || pki_die 'Migration provenance is missing, replaced, or ambiguous'
if [[ -d $PROVENANCE_STAGE ]]; then
  pki_validate_provenance_manifest "$PROVENANCE_STAGE" "${PKI_RECORD[provenance_manifest]}" "${PKI_RECORD[provenance_manifest_identity]}" "${PKI_RECORD[provenance_manifest_sha256]}"
elif [[ -d $PROVENANCE_DIR ]]; then
  pki_validate_provenance_manifest "$PROVENANCE_DIR" "$PROVENANCE_DIR/provenance-manifest" "${PKI_RECORD[provenance_manifest_identity]}" "${PKI_RECORD[provenance_manifest_sha256]}"
fi
pki_require_file_identity "${PKI_RECORD[backup_receipt]}" "${PKI_RECORD[receipt_identity]}" 'Migration backup receipt'
verify_bound_file "$ISSUER_LEDGER" "${PKI_RECORD[issuer_ledger_identity]}" "${PKI_RECORD[issuer_ledger_sha256]}" 'Migration issuer ledger'
verify_bound_file "$QUARANTINE_LEDGER" "${PKI_RECORD[quarantine_ledger_identity]}" "${PKI_RECORD[quarantine_ledger_sha256]}" 'Migration quarantine ledger'
services_current=$(pki_file_identity_or_absent "$TXN_DIR/services")
[[ $services_current == "${PKI_RECORD[services_identity]}" || $services_current != absent && $(pki_file_identity "$TXN_DIR/services") == "${PKI_RECORD[services_identity]}" ]] || pki_die 'Recovery service set changed'
services_digest=$(sha256sum "$TXN_DIR/services"); [[ ${services_digest%% *} == "${PKI_RECORD[services_sha256]}" ]] || pki_die 'Recovery service set changed'

write_recovery_journal() {
  local phase=$1 committed=${2:-false} key value content=''
  PKI_RECORD[phase]=$phase; PKI_RECORD[committed]=$committed
  while IFS= read -r key; do value=${PKI_RECORD[$key]}; content+="$key=$value
"; done < <(printf '%s\n' "${!PKI_RECORD[@]}" | LC_ALL=C sort)
  pki_write_journal "$JOURNAL" "$content"
}
migration_checkpoint() { PKI_RECORD[recovery_action]=$ACTION; PKI_RECORD[recovery_step]=$1; write_recovery_journal recovering; recover_fault "$1"; }

authority_location() {
  local legacy=$1 generation=$2 identity=$3 label=$4 legacy_exists=false generation_exists=false
  [[ ! -e $legacy && ! -L $legacy ]] || legacy_exists=true; [[ ! -e $generation && ! -L $generation ]] || generation_exists=true
  [[ $legacy_exists != "$generation_exists" ]] || pki_die "$label paths are simultaneously present or absent"
  if [[ $legacy_exists == true ]]; then [[ -d $legacy && ! -L $legacy && $(stat -c '%d:%i' "$legacy") == "$identity" ]] || pki_die "$label legacy identity changed"; AUTHORITY_LOCATION=$legacy
  else [[ -d $generation && ! -L $generation && $(stat -c '%d:%i' "$generation") == "$identity" ]] || pki_die "$label generation identity changed"; AUTHORITY_LOCATION=$generation; fi
}

allowed_file_state() { local path=$1 label=$2; shift 2; local current expected; current=$(pki_file_identity_or_absent "$path"); for expected in "$@"; do [[ $current != "$expected" ]] || return 0; done; pki_die "$label is not in a journaled identity state"; }

# Validate every category before the first recovery mutation.
authority_location "$LEGACY_ROOT" "$NEW_ROOT" "$ROOT_ID" 'Root authority'; ROOT_LOCATION=$AUTHORITY_LOCATION
authority_location "$LEGACY_INT" "$NEW_INT" "$INT_ID" 'Intermediate authority'; INT_LOCATION=$AUTHORITY_LOCATION
allowed_file_state "$ROOT_LOCATION/openssl.cnf" 'Root OpenSSL configuration' "${PKI_RECORD[root_config_original_identity]}" "${PKI_RECORD[root_config_published_identity]}" "${PKI_RECORD[root_config_rollback_identity]}"
allowed_file_state "$INT_LOCATION/openssl.cnf" 'Intermediate OpenSSL configuration' "${PKI_RECORD[intermediate_config_original_identity]}" "${PKI_RECORD[intermediate_config_published_identity]}" "${PKI_RECORD[intermediate_config_rollback_identity]}"
allowed_file_state "$ROOT_RESERVATION" 'Root reservation' "${PKI_RECORD[root_reservation_original_identity]}" "${PKI_RECORD[root_reservation_reserved_identity]}" "${PKI_RECORD[root_reservation_consumed_identity]}" "${PKI_RECORD[root_reservation_rollback_identity]}"
allowed_file_state "$INT_RESERVATION" 'Intermediate reservation' "${PKI_RECORD[intermediate_reservation_original_identity]}" "${PKI_RECORD[intermediate_reservation_reserved_identity]}" "${PKI_RECORD[intermediate_reservation_consumed_identity]}" "${PKI_RECORD[intermediate_reservation_rollback_identity]}"
allowed_file_state "$BACKUP_SESSION" 'Backup session record' "${PKI_RECORD[backup_session_original_identity]}" "${PKI_RECORD[backup_session_published_identity]}"
allowed_file_state "$ACTIVE_MANIFEST" 'Active issuer manifest' "${PKI_RECORD[active_original_identity]}" "${PKI_RECORD[active_published_identity]}"
while IFS='|' read -r service original published extra; do [[ -n $service && -z ${extra:-} ]] || pki_die 'Migration issuer ledger has invalid content'; pki_validate_service_name "$service"; allowed_file_state "$(pki_service_issuer "$service")" "Service $service issuer" "$original" "$published"; done <"$ISSUER_LEDGER"
while IFS='|' read -r basename identity extra; do [[ $basename =~ ^(pki\.env|openssl-root\.cnf\.tpl|openssl-intermediate\.cnf\.tpl|openssl-service\.cnf\.tpl)$ && -z ${extra:-} ]] || pki_die 'Migration quarantine ledger has invalid content'; source="$PKI_DIR/$basename"; destination="$TXN_DIR/quarantine/$basename"; source_state=$(pki_file_identity_or_absent "$source"); destination_state=$(pki_file_identity_or_absent "$destination"); [[ $source_state == "$identity" && $destination_state == absent || $source_state == absent && $destination_state == "$identity" ]] || pki_die "Quarantine entry is ambiguous or replaced: $basename"; done <"$QUARANTINE_LEDGER"
if [[ $ACTION == rollback ]]; then
  [[ $(pki_file_identity_or_absent "$ROOT_LOCATION/openssl.cnf") != "${PKI_RECORD[root_config_published_identity]}" ]] || pki_require_file_identity "$TXN_DIR/root-openssl.rollback" "${PKI_RECORD[root_config_rollback_identity]}" 'Root OpenSSL rollback stage'
  [[ $(pki_file_identity_or_absent "$INT_LOCATION/openssl.cnf") != "${PKI_RECORD[intermediate_config_published_identity]}" ]] || pki_require_file_identity "$TXN_DIR/intermediate-openssl.rollback" "${PKI_RECORD[intermediate_config_rollback_identity]}" 'Intermediate OpenSSL rollback stage'
  [[ $(pki_file_identity_or_absent "$ROOT_RESERVATION") == "${PKI_RECORD[root_reservation_rollback_identity]}" ]] || pki_require_file_identity "$TXN_DIR/root-abandoned.publish" "${PKI_RECORD[root_reservation_rollback_identity]}" 'Root abandoned reservation stage'
  [[ $(pki_file_identity_or_absent "$INT_RESERVATION") == "${PKI_RECORD[intermediate_reservation_rollback_identity]}" ]] || pki_require_file_identity "$TXN_DIR/intermediate-abandoned.publish" "${PKI_RECORD[intermediate_reservation_rollback_identity]}" 'Intermediate abandoned reservation stage'
else
  [[ $(pki_file_identity_or_absent "$BACKUP_SESSION") != "${PKI_RECORD[backup_session_original_identity]}" ]] || pki_require_file_identity "$TXN_DIR/backup-session.publish" "${PKI_RECORD[backup_session_published_identity]}" 'Staged backup session'
  for record in "$ROOT_RESERVATION|${PKI_RECORD[root_reservation_original_identity]}|${PKI_RECORD[root_reservation_reserved_identity]}|${PKI_RECORD[root_reservation_consumed_identity]}|$TXN_DIR/root-reserved.publish|$TXN_DIR/root-consumed.publish" "$INT_RESERVATION|${PKI_RECORD[intermediate_reservation_original_identity]}|${PKI_RECORD[intermediate_reservation_reserved_identity]}|${PKI_RECORD[intermediate_reservation_consumed_identity]}|$TXN_DIR/intermediate-reserved.publish|$TXN_DIR/intermediate-consumed.publish"; do path=${record%%|*}; rest=${record#*|}; original=${rest%%|*}; rest=${rest#*|}; reserved=${rest%%|*}; rest=${rest#*|}; consumed=${rest%%|*}; rest=${rest#*|}; reserved_stage=${rest%%|*}; consumed_stage=${rest#*|}; current=$(pki_file_identity_or_absent "$path"); [[ $current != "$original" ]] || pki_require_file_identity "$reserved_stage" "$reserved" 'Staged reserved generation'; [[ $current == "$consumed" ]] || pki_require_file_identity "$consumed_stage" "$consumed" 'Staged consumed generation'; done
  [[ $(pki_file_identity_or_absent "$ROOT_LOCATION/openssl.cnf") != "${PKI_RECORD[root_config_original_identity]}" ]] || pki_require_file_identity "$TXN_DIR/root-openssl.new" "${PKI_RECORD[root_config_published_identity]}" 'Staged root generation configuration'
  [[ $(pki_file_identity_or_absent "$INT_LOCATION/openssl.cnf") != "${PKI_RECORD[intermediate_config_original_identity]}" ]] || pki_require_file_identity "$TXN_DIR/intermediate-openssl.new" "${PKI_RECORD[intermediate_config_published_identity]}" 'Staged intermediate generation configuration'
  while IFS='|' read -r service original published; do [[ $(pki_file_identity_or_absent "$(pki_service_issuer "$service")") != "$original" ]] || pki_require_file_identity "$TXN_DIR/issuer-stage/$service" "$published" "Staged issuer $service"; done <"$ISSUER_LEDGER"
  [[ $(pki_file_identity_or_absent "$ACTIVE_MANIFEST") != "${PKI_RECORD[active_original_identity]}" ]] || pki_require_file_identity "$TXN_DIR/active.publish" "${PKI_RECORD[active_published_identity]}" 'Staged active issuer'
fi

if [[ $ACTION == rollback ]]; then
  current=$(pki_file_identity_or_absent "$ACTIVE_MANIFEST"); if [[ $current == "${PKI_RECORD[active_published_identity]}" ]]; then migration_checkpoint rollback-active-pending; pki_remove_identity_file "$ACTIVE_MANIFEST" "$current" || pki_die 'Cannot remove journaled active issuer manifest'; migration_checkpoint rollback-active-done; fi
  while IFS='|' read -r service original published; do issuer=$(pki_service_issuer "$service"); current=$(pki_file_identity_or_absent "$issuer"); if [[ $current == "$published" ]]; then migration_checkpoint "rollback-issuer-$service-pending"; pki_remove_identity_file "$issuer" "$current" || pki_die "Cannot remove journaled issuer: $service"; migration_checkpoint "rollback-issuer-$service-done"; fi; done <"$ISSUER_LEDGER"
  while IFS='|' read -r basename identity; do source="$PKI_DIR/$basename"; destination="$TXN_DIR/quarantine/$basename"; if [[ $(pki_file_identity_or_absent "$destination") == "$identity" ]]; then migration_checkpoint "rollback-quarantine-$basename-pending"; pki_require_file_identity "$source" absent 'Quarantine restore destination'; mv -T -- "$destination" "$source"; pki_fsync_rename_parents "$(dirname -- "$destination")" "$(dirname -- "$source")"; pki_require_file_identity "$source" "$identity" 'Restored quarantine entry'; migration_checkpoint "rollback-quarantine-$basename-done"; fi; done <"$QUARANTINE_LEDGER"
  for record in "$ROOT_LOCATION|root|${PKI_RECORD[root_config_original_identity]}|${PKI_RECORD[root_config_published_identity]}|${PKI_RECORD[root_config_rollback_identity]}|$TXN_DIR/root-openssl.rollback" "$INT_LOCATION|intermediate|${PKI_RECORD[intermediate_config_original_identity]}|${PKI_RECORD[intermediate_config_published_identity]}|${PKI_RECORD[intermediate_config_rollback_identity]}|$TXN_DIR/intermediate-openssl.rollback"; do location=${record%%|*}; rest=${record#*|}; label=${rest%%|*}; rest=${rest#*|}; original=${rest%%|*}; rest=${rest#*|}; published=${rest%%|*}; rest=${rest#*|}; rollback=${rest%%|*}; stage=${rest#*|}; config="$location/openssl.cnf"; current=$(pki_file_identity_or_absent "$config"); if [[ $current == "$published" ]]; then migration_checkpoint "rollback-config-$label-pending"; pki_publish_staged_file "$stage" "$config"; migration_checkpoint "rollback-config-$label-done"; elif [[ $current != "$original" && $current != "$rollback" ]]; then pki_die "$label OpenSSL configuration changed before rollback"; fi; done
  authority_location "$LEGACY_INT" "$NEW_INT" "$INT_ID" 'Intermediate authority'; if [[ $AUTHORITY_LOCATION == "$NEW_INT" ]]; then migration_checkpoint rollback-intermediate-rename-pending; pki_require_file_identity "$LEGACY_INT" absent 'Legacy intermediate destination'; mv -T -- "$NEW_INT" "$LEGACY_INT"; pki_fsync_rename_parents "$(dirname -- "$NEW_INT")" "$(dirname -- "$LEGACY_INT")"; migration_checkpoint rollback-intermediate-rename-done; fi
  authority_location "$LEGACY_ROOT" "$NEW_ROOT" "$ROOT_ID" 'Root authority'; if [[ $AUTHORITY_LOCATION == "$NEW_ROOT" ]]; then migration_checkpoint rollback-root-rename-pending; pki_require_file_identity "$LEGACY_ROOT" absent 'Legacy root destination'; mv -T -- "$NEW_ROOT" "$LEGACY_ROOT"; pki_fsync_rename_parents "$(dirname -- "$NEW_ROOT")" "$(dirname -- "$LEGACY_ROOT")"; migration_checkpoint rollback-root-rename-done; fi
  for record in "$ROOT_RESERVATION|root|${PKI_RECORD[root_reservation_rollback_identity]}|$TXN_DIR/root-abandoned.publish" "$INT_RESERVATION|intermediate|${PKI_RECORD[intermediate_reservation_rollback_identity]}|$TXN_DIR/intermediate-abandoned.publish"; do path=${record%%|*}; rest=${record#*|}; kind=${rest%%|*}; rest=${rest#*|}; rollback=${rest%%|*}; stage=${rest#*|}; current=$(pki_file_identity_or_absent "$path"); if [[ $current != "$rollback" ]]; then migration_checkpoint "rollback-reservation-$kind-pending"; pki_publish_staged_file "$stage" "$path"; migration_checkpoint "rollback-reservation-$kind-done"; fi; done
  current=$(pki_file_identity_or_absent "$BACKUP_SESSION"); if [[ $current == "${PKI_RECORD[backup_session_published_identity]}" ]]; then migration_checkpoint rollback-backup-session-pending; pki_remove_identity_file "$BACKUP_SESSION" "$current" || pki_die 'Cannot remove backup session record'; migration_checkpoint rollback-backup-session-done; fi
  if [[ -d $PROVENANCE_STAGE ]]; then migration_checkpoint rollback-provenance-pending; pki_remove_journaled_tree "$PROVENANCE_STAGE" "$PROVENANCE_IDENTITY" "$(dirname -- "$PROVENANCE_STAGE")" || pki_die 'Cannot remove migration provenance stage'; migration_checkpoint rollback-provenance-done
  elif [[ -d $PROVENANCE_DIR ]]; then migration_checkpoint rollback-provenance-pending; pki_remove_journaled_tree "$PROVENANCE_DIR" "$PROVENANCE_IDENTITY" "$(dirname -- "$PROVENANCE_DIR")" || pki_die 'Cannot remove migration provenance'; migration_checkpoint rollback-provenance-done; fi
  write_recovery_journal rolled-back true; rm -f -- "$MARKER"; pki_fsync "$(dirname -- "$MARKER")"; pki_ok "Rolled back migration transaction: $TRANSACTION"; exit 0
fi

# Resume each mutation only from its exact original identity; exact published state is a no-op.
current=$(pki_file_identity_or_absent "$BACKUP_SESSION"); if [[ $current == "${PKI_RECORD[backup_session_original_identity]}" ]]; then migration_checkpoint resume-backup-session-pending; stage="$TXN_DIR/backup-session.publish"; pki_publish_staged_file "$stage" "$BACKUP_SESSION"; migration_checkpoint resume-backup-session-done; fi
for record in "$ROOT_RESERVATION|root|${PKI_RECORD[root_reservation_original_identity]}|${PKI_RECORD[root_reservation_reserved_identity]}|$TXN_DIR/root-reserved.publish" "$INT_RESERVATION|intermediate|${PKI_RECORD[intermediate_reservation_original_identity]}|${PKI_RECORD[intermediate_reservation_reserved_identity]}|$TXN_DIR/intermediate-reserved.publish"; do path=${record%%|*}; rest=${record#*|}; kind=${rest%%|*}; rest=${rest#*|}; original=${rest%%|*}; rest=${rest#*|}; published=${rest%%|*}; stage=${rest#*|}; current=$(pki_file_identity_or_absent "$path"); if [[ $current == "$original" ]]; then migration_checkpoint "resume-reservation-$kind-pending"; pki_publish_staged_file "$stage" "$path"; migration_checkpoint "resume-reservation-$kind-done"; elif [[ $current != "$published" && $current != "${PKI_RECORD[root_reservation_consumed_identity]}" && $current != "${PKI_RECORD[intermediate_reservation_consumed_identity]}" ]]; then pki_die 'Reservation cannot be resumed from its current identity'; fi; done
write_recovery_journal reserved
authority_location "$LEGACY_ROOT" "$NEW_ROOT" "$ROOT_ID" 'Root authority'; if [[ $AUTHORITY_LOCATION == "$LEGACY_ROOT" ]]; then migration_checkpoint resume-root-rename-pending; pki_require_file_identity "$NEW_ROOT" absent 'Root generation destination'; mv -T -- "$LEGACY_ROOT" "$NEW_ROOT"; pki_fsync_rename_parents "$(dirname -- "$LEGACY_ROOT")" "$(dirname -- "$NEW_ROOT")"; migration_checkpoint resume-root-rename-done; fi; write_recovery_journal root-renamed
authority_location "$LEGACY_INT" "$NEW_INT" "$INT_ID" 'Intermediate authority'; if [[ $AUTHORITY_LOCATION == "$LEGACY_INT" ]]; then migration_checkpoint resume-intermediate-rename-pending; pki_require_file_identity "$NEW_INT" absent 'Intermediate generation destination'; mv -T -- "$LEGACY_INT" "$NEW_INT"; pki_fsync_rename_parents "$(dirname -- "$LEGACY_INT")" "$(dirname -- "$NEW_INT")"; migration_checkpoint resume-intermediate-rename-done; fi; write_recovery_journal intermediate-renamed
for record in "$NEW_ROOT/openssl.cnf|root|${PKI_RECORD[root_config_original_identity]}|${PKI_RECORD[root_config_published_identity]}|$TXN_DIR/root-openssl.new" "$NEW_INT/openssl.cnf|intermediate|${PKI_RECORD[intermediate_config_original_identity]}|${PKI_RECORD[intermediate_config_published_identity]}|$TXN_DIR/intermediate-openssl.new"; do path=${record%%|*}; rest=${record#*|}; label=${rest%%|*}; rest=${rest#*|}; original=${rest%%|*}; rest=${rest#*|}; published=${rest%%|*}; stage=${rest#*|}; current=$(pki_file_identity_or_absent "$path"); if [[ $current == "$original" ]]; then migration_checkpoint "resume-config-$label-pending"; pki_publish_staged_file "$stage" "$path"; migration_checkpoint "resume-config-$label-done"; elif [[ $current != "$published" ]]; then pki_die 'Generation configuration cannot be resumed from its current identity'; fi; done
write_recovery_journal configs-published
while IFS='|' read -r service original published; do issuer=$(pki_service_issuer "$service"); stage="$TXN_DIR/issuer-stage/$service"; current=$(pki_file_identity_or_absent "$issuer"); if [[ $current == "$original" ]]; then migration_checkpoint "resume-issuer-$service-pending"; pki_publish_staged_file "$stage" "$issuer"; migration_checkpoint "resume-issuer-$service-done"; elif [[ $current != "$published" ]]; then pki_die "Issuer cannot be resumed from its current identity: $service"; fi; done <"$ISSUER_LEDGER"
write_recovery_journal issuers-published
while IFS='|' read -r basename identity; do source="$PKI_DIR/$basename"; destination="$TXN_DIR/quarantine/$basename"; if [[ $(pki_file_identity_or_absent "$source") == "$identity" ]]; then migration_checkpoint "resume-quarantine-$basename-pending"; pki_require_file_identity "$destination" absent 'Quarantine publication destination'; mv -T -- "$source" "$destination"; pki_fsync_rename_parents "$(dirname -- "$source")" "$(dirname -- "$destination")"; migration_checkpoint "resume-quarantine-$basename-done"; elif [[ $(pki_file_identity_or_absent "$destination") != "$identity" ]]; then pki_die "Quarantine entry cannot be resumed: $basename"; fi; done <"$QUARANTINE_LEDGER"
write_recovery_journal quarantined
for record in "$ROOT_RESERVATION|root|${PKI_RECORD[root_reservation_reserved_identity]}|${PKI_RECORD[root_reservation_consumed_identity]}|$TXN_DIR/root-consumed.publish" "$INT_RESERVATION|intermediate|${PKI_RECORD[intermediate_reservation_reserved_identity]}|${PKI_RECORD[intermediate_reservation_consumed_identity]}|$TXN_DIR/intermediate-consumed.publish"; do path=${record%%|*}; rest=${record#*|}; kind=${rest%%|*}; rest=${rest#*|}; reserved=${rest%%|*}; rest=${rest#*|}; consumed=${rest%%|*}; stage=${rest#*|}; current=$(pki_file_identity_or_absent "$path"); if [[ $current == "$reserved" ]]; then migration_checkpoint "resume-consume-$kind-pending"; pki_publish_staged_file "$stage" "$path"; migration_checkpoint "resume-consume-$kind-done"; elif [[ $current != "$consumed" ]]; then pki_die 'Reservation cannot be consumed from its current identity'; fi; done
write_recovery_journal active-pending
current=$(pki_file_identity_or_absent "$ACTIVE_MANIFEST"); if [[ $current == "${PKI_RECORD[active_original_identity]}" ]]; then migration_checkpoint resume-active-pending; stage="$TXN_DIR/active.publish"; pki_publish_staged_file "$stage" "$ACTIVE_MANIFEST"; migration_checkpoint resume-active-done; elif [[ $current != "${PKI_RECORD[active_published_identity]}" ]]; then pki_die 'Active issuer cannot be resumed from its current identity'; fi
if [[ -d $PROVENANCE_STAGE ]]; then migration_checkpoint resume-provenance-pending; mv -T -- "$PROVENANCE_STAGE" "$PROVENANCE_DIR"; pki_fsync_rename_parents "$(dirname -- "$PROVENANCE_STAGE")" "$(dirname -- "$PROVENANCE_DIR")"; [[ $(pki_dir_identity "$PROVENANCE_DIR") == "$PROVENANCE_IDENTITY" ]] || pki_die 'Migration provenance identity changed during recovery'; migration_checkpoint resume-provenance-done; fi
write_recovery_journal complete true; rm -f -- "$MARKER"; pki_fsync "$(dirname -- "$MARKER")"; pki_remove_journaled_tree "$TXN_DIR" "${PKI_RECORD[transaction_identity]}" "$(dirname -- "$TXN_DIR")" || pki_die 'Cannot remove committed migration transaction staging'; pki_ok "Resumed migration transaction: $TRANSACTION"
