SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
COMMON_PATH=${PLATFORM_TOOLS_LIB_DIR:-}
if [[ -n $COMMON_PATH ]]; then COMMON_PATH=${COMMON_PATH}/platform-pki-common.sh
elif [[ -r ${SCRIPT_DIR}/../lib/platform-pki-common.sh ]]; then COMMON_PATH=${SCRIPT_DIR}/../lib/platform-pki-common.sh
else COMMON_PATH=${PLATFORM_TOOLS_SHARE_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/platform-tools}/lib/platform-pki-common.sh; fi
[[ -r $COMMON_PATH ]] || { printf '[ERROR] platform-pki-common.sh not found\n' >&2; exit 1; }
# shellcheck source=../../../../lib/platform-pki-common.sh disable=SC1091
source "$COMMON_PATH"

NAMESPACE=${args[--namespace]:-$(pki_default_namespace)}; PKI_DIR=${args[--pki-dir]:-}
TRANSACTION=${args[--transaction]}; ACTION=${args[--action]}; YES=false; [[ -v args[--yes] ]] && YES=true
NAMESPACE=$(pki_expand_path "$NAMESPACE"); PKI_DIR=${PKI_DIR:-${NAMESPACE}/pki}; PKI_DIR=$(pki_expand_path "$PKI_DIR")
[[ $TRANSACTION =~ ^(migrate|root-bootstrap|intermediate-bootstrap)-[0-9]{8}-[0-9]{6}-[0-9]+$ ]] || pki_die 'Recovery transaction ID is invalid'
if [[ $YES != true ]]; then
  [[ -t 0 ]] || pki_die 'Recovery requires a TTY or --yes'
  printf 'Type recover %s %s to continue: ' "$TRANSACTION" "$ACTION" >&2
  IFS= read -r confirmation; [[ $confirmation == "recover $TRANSACTION $ACTION" ]] || pki_die 'Recovery confirmation did not match'
fi
pki_require_pki_dir; pki_prepare_control_state
ROOT_LOCK=$(pki_root_operation_lock); INTERMEDIATE_LOCK=$(pki_intermediate_operation_lock); INVENTORY_LOCK=$(pki_inventory_operation_lock); EXPORT_LOCK=$(pki_export_operation_lock)
finish_recover() { local status=$?; trap - EXIT; [[ ${EXPORT_LOCK_HELD:-false} != true ]] || pki_release_operation_lock "$EXPORT_LOCK" || status=1; [[ ${INVENTORY_LOCK_HELD:-false} != true ]] || pki_release_operation_lock "$INVENTORY_LOCK" || status=1; [[ ${INTERMEDIATE_LOCK_HELD:-false} != true ]] || pki_release_operation_lock "$INTERMEDIATE_LOCK" || status=1; [[ ${ROOT_LOCK_HELD:-false} != true ]] || pki_release_operation_lock "$ROOT_LOCK" || status=1; exit "$status"; }
trap finish_recover EXIT
pki_acquire_operation_lock "$ROOT_LOCK" 'root CA operation'; ROOT_LOCK_HELD=true
pki_acquire_operation_lock "$INTERMEDIATE_LOCK" 'intermediate CA operation'; INTERMEDIATE_LOCK_HELD=true
pki_acquire_operation_lock "$INVENTORY_LOCK" 'inventory operation'; INVENTORY_LOCK_HELD=true
pki_acquire_operation_lock "$EXPORT_LOCK" 'export operation'; EXPORT_LOCK_HELD=true
JOURNAL=$(pki_recovery_journal); MARKER=$(pki_recovery_marker)
pki_read_state_record "$JOURNAL" 'PKI recovery journal'
[[ ${PKI_RECORD[transaction]:-} == "$TRANSACTION" && ${PKI_RECORD[committed]:-} == false ]] || pki_die 'Recovery journal does not describe the requested uncommitted transaction'
recover_fault() { [[ ${PLATFORM_PKI_RECOVER_CRASH_AT:-} != "$1" ]] || kill -KILL "$$"; }
write_loaded_journal() {
  local phase=$1 committed=${2:-false} key value content=''
  PKI_RECORD[phase]=$phase; PKI_RECORD[committed]=$committed
  while IFS= read -r key; do value=${PKI_RECORD[$key]}; content+="$key=$value
"; done < <(printf '%s\n' "${!PKI_RECORD[@]}" | LC_ALL=C sort)
  pki_write_journal "$JOURNAL" "$content"
}
checkpoint_recovery() { PKI_RECORD[recovery_step]=$1; write_loaded_journal recovering; recover_fault "$1"; }
file_state_allowed() {
  local path=$1 label=$2 current full expected
  shift 2
  current=$(pki_file_identity_or_absent "$path"); full=$current
  [[ $current == absent ]] || full=$(pki_file_identity "$path")
  for expected in "$@"; do [[ $current != "$expected" && $full != "$expected" ]] || return 0; done
  pki_die "$label is not in a journaled identity state"
}
if [[ ${PKI_RECORD[operation]:-} == root-bootstrap || ${PKI_RECORD[operation]:-} == intermediate-bootstrap ]]; then
  if [[ ${PKI_RECORD[operation]} == root-bootstrap ]]; then [[ $ACTION == rollback ]] || pki_die 'Root bootstrap recovery supports only rollback'
  elif [[ $ACTION == resume ]]; then [[ ${PKI_RECORD[phase]} == cleanup-* || ${PKI_RECORD[recovery_step]:-} == cleanup-* ]] || pki_die 'Intermediate bootstrap resume is limited to sensitive-stage cleanup'
  else [[ $ACTION == rollback ]] || pki_die 'Intermediate bootstrap recovery action is invalid'; fi
  for field in schema operation transaction phase stage_dir stage_identity transaction_dir transaction_identity reservation reservation_reserved_identity reservation_consumed_identity reservation_abandoned_identity recovery_action recovery_step committed; do [[ -v PKI_RECORD[$field] ]] || pki_die "Bootstrap recovery journal is missing field: $field"; done
  [[ ${PKI_RECORD[schema]} == 3 ]] || pki_die 'Bootstrap recovery journal schema is unsupported'
  TXN_DIR=${PKI_RECORD[transaction_dir]}; [[ $TXN_DIR == "$PKI_DIR/state/rollover/$TRANSACTION" && -d $TXN_DIR && ! -L $TXN_DIR && $(pki_dir_identity "$TXN_DIR") == "${PKI_RECORD[transaction_identity]}" ]] || pki_die 'Bootstrap recovery transaction directory is missing, replaced, or unsafe'
  stage=${PKI_RECORD[stage_dir]}; stage_identity=${PKI_RECORD[stage_identity]}; reservation=${PKI_RECORD[reservation]}; abandoned_stage="$TXN_DIR/reservation-abandoned"
  file_state_allowed "$reservation" 'Bootstrap reservation' absent "${PKI_RECORD[reservation_reserved_identity]}" "${PKI_RECORD[reservation_consumed_identity]}" "${PKI_RECORD[reservation_abandoned_identity]}"
  [[ $(pki_file_identity_or_absent "$reservation") == "${PKI_RECORD[reservation_abandoned_identity]}" ]] || pki_require_file_identity "$abandoned_stage" "${PKI_RECORD[reservation_abandoned_identity]}" 'Abandoned bootstrap reservation stage'
  [[ $stage == none || ! -e $stage && ! -L $stage || -d $stage && ! -L $stage && $(pki_dir_identity "$stage") == "$stage_identity" ]] || pki_die 'Bootstrap staging identity changed'
  PKI_RECORD[recovery_action]=rollback
  if [[ ${PKI_RECORD[operation]} == root-bootstrap ]]; then
    for field in generation authority_dir authority_identity bootstrap_identity; do [[ -v PKI_RECORD[$field] ]] || pki_die "Root bootstrap recovery journal is missing field: $field"; done
    generation=${PKI_RECORD[generation]}; pki_validate_root_generation "$generation"; authority=${PKI_RECORD[authority_dir]}; authority_identity=${PKI_RECORD[authority_identity]}
    [[ $authority == "$(pki_root_authority_dir "$generation")" && $reservation == "$(pki_generation_reservation "$generation")" ]] || pki_die 'Root bootstrap recovery paths are invalid'
    [[ ! -e $authority && ! -L $authority || -d $authority && ! -L $authority && $authority_identity != none && $(pki_dir_identity "$authority") == "$authority_identity" ]] || pki_die 'Root bootstrap authority identity changed'
    bootstrap=$(pki_bootstrap_root_manifest); file_state_allowed "$bootstrap" 'Bootstrap root manifest' absent "${PKI_RECORD[bootstrap_identity]}"
    if [[ $(pki_file_identity_or_absent "$bootstrap") != absent ]]; then checkpoint_recovery rollback-bootstrap-pending; pki_remove_identity_file "$bootstrap" "${PKI_RECORD[bootstrap_identity]}" || pki_die 'Cannot remove bootstrap root manifest'; checkpoint_recovery rollback-bootstrap-done; fi
  else
    for field in root_generation intermediate_generation root_dir intermediate_dir intermediate_identity issued_serial bootstrap_fingerprint active_identity bootstrap_identity bootstrap_rollback_identity root_mutated root_stage root_stage_identity; do [[ -v PKI_RECORD[$field] ]] || pki_die "Intermediate recovery journal is missing field: $field"; done
    root_generation=${PKI_RECORD[root_generation]}; generation=${PKI_RECORD[intermediate_generation]}; pki_validate_root_generation "$root_generation"; pki_validate_intermediate_generation "$generation"; [[ $generation == "$root_generation"-i* ]] || pki_die 'Intermediate bootstrap generations are mismatched'
    root_dir=${PKI_RECORD[root_dir]}; authority=${PKI_RECORD[intermediate_dir]}; authority_identity=${PKI_RECORD[intermediate_identity]}; issued_serial=${PKI_RECORD[issued_serial]}
    [[ $root_dir == "$(pki_root_authority_dir "$root_generation")" && $authority == "$(pki_intermediate_authority_dir "$generation")" && $reservation == "$(pki_generation_reservation "$generation")" ]] || pki_die 'Intermediate bootstrap recovery paths are invalid'
    root_stage=${PKI_RECORD[root_stage]}; root_stage_identity=${PKI_RECORD[root_stage_identity]}
    if [[ $root_stage != none ]]; then [[ $root_stage == "$stage/root" && $root_stage_identity != none ]] || pki_die 'Sensitive root signing stage path is invalid'; [[ ! -e $root_stage && ! -L $root_stage || -d $root_stage && ! -L $root_stage && $(pki_dir_identity "$root_stage") == "$root_stage_identity" ]] || pki_die 'Sensitive root signing stage identity changed'; fi
    [[ ! -e $authority && ! -L $authority || -d $authority && ! -L $authority && $authority_identity != none && $(pki_dir_identity "$authority") == "$authority_identity" ]] || pki_die 'Intermediate bootstrap authority identity changed'
    active=$(pki_active_issuer_manifest); file_state_allowed "$active" 'Active issuer manifest' absent "${PKI_RECORD[active_identity]}"
    bootstrap=$(pki_bootstrap_root_manifest); bootstrap_stage="$TXN_DIR/bootstrap-rollback"; file_state_allowed "$bootstrap" 'Bootstrap root manifest' absent "${PKI_RECORD[bootstrap_identity]}" "${PKI_RECORD[bootstrap_rollback_identity]}"
    [[ $(pki_file_identity_or_absent "$bootstrap") != absent ]] || pki_require_file_identity "$bootstrap_stage" "${PKI_RECORD[bootstrap_rollback_identity]}" 'Bootstrap rollback stage'
    if [[ ${PKI_RECORD[root_mutated]} == true ]]; then
      declare -A db_path=() db_backup=(); db_keys=(index index_attr serial crlnumber index_old index_attr_old serial_old crlnumber_old newcert)
      db_path[index]="$root_dir/index.txt"; db_path[index_attr]="$root_dir/index.txt.attr"; db_path[serial]="$root_dir/serial"; db_path[crlnumber]="$root_dir/crlnumber"; db_path[index_old]="$root_dir/index.txt.old"; db_path[index_attr_old]="$root_dir/index.txt.attr.old"; db_path[serial_old]="$root_dir/serial.old"; db_path[crlnumber_old]="$root_dir/crlnumber.old"; db_path[newcert]="$root_dir/newcerts/$issued_serial.pem"
      backup="$stage/root-backup"; db_backup[index]="$backup/index.txt"; db_backup[index_attr]="$backup/index.txt.attr"; db_backup[serial]="$backup/serial"; db_backup[crlnumber]="$backup/crlnumber"; db_backup[index_old]="$backup/index.txt.old"; db_backup[index_attr_old]="$backup/index.txt.attr.old"; db_backup[serial_old]="$backup/serial.old"; db_backup[crlnumber_old]="$backup/crlnumber.old"; db_backup[newcert]=none
      for key in "${db_keys[@]}"; do for suffix in pre_identity post_identity backup_identity; do field="root_${key}_${suffix}"; [[ -v PKI_RECORD[$field] ]] || pki_die "Intermediate recovery journal is missing field: $field"; done; file_state_allowed "${db_path[$key]}" "Root $key state" "${PKI_RECORD[root_${key}_pre_identity]}" "${PKI_RECORD[root_${key}_post_identity]}" "${PKI_RECORD[root_${key}_backup_identity]}"; current=$(pki_file_identity_or_absent "${db_path[$key]}"); if [[ $current == "${PKI_RECORD[root_${key}_post_identity]}" && ${PKI_RECORD[root_${key}_pre_identity]} != absent ]]; then pki_require_file_identity "${db_backup[$key]}" "${PKI_RECORD[root_${key}_backup_identity]}" "Root $key rollback copy"; fi; done
    fi
    if [[ $ACTION == resume ]]; then
      [[ -d $authority && ! -L $authority && $(pki_dir_identity "$authority") == "$authority_identity" ]] || pki_die 'Published intermediate authority is not complete'
      pki_require_file_identity "$active" "${PKI_RECORD[active_identity]}" 'Active issuer manifest'; pki_require_file_identity "$bootstrap" absent 'Bootstrap root manifest'; pki_require_file_identity "$reservation" "${PKI_RECORD[reservation_consumed_identity]}" 'Consumed intermediate reservation'
      for key in "${db_keys[@]}"; do pki_require_file_identity "${db_path[$key]}" "${PKI_RECORD[root_${key}_post_identity]}" "Published root $key state"; done
      if [[ $root_stage != none && -d $root_stage ]]; then checkpoint_recovery cleanup-pending; pki_remove_journaled_tree "$root_stage" "$root_stage_identity" "$stage" || pki_die 'Cannot remove sensitive root signing stage'; fi
      checkpoint_recovery cleanup-done; write_loaded_journal complete true; rm -f -- "$MARKER"; pki_fsync "$(dirname -- "$MARKER")"
      [[ $stage == none || ! -d $stage ]] || pki_remove_journaled_tree "$stage" "$stage_identity" "$(dirname -- "$stage")" || pki_die 'Cannot remove intermediate bootstrap staging'
      pki_ok "Completed sensitive-stage cleanup for intermediate bootstrap transaction: $TRANSACTION"; exit 0
    fi
    if [[ $(pki_file_identity_or_absent "$active") != absent ]]; then checkpoint_recovery rollback-active-pending; pki_remove_identity_file "$active" "${PKI_RECORD[active_identity]}" || pki_die 'Cannot remove active issuer manifest'; checkpoint_recovery rollback-active-done; fi
    if [[ $(pki_file_identity_or_absent "$bootstrap") == absent ]]; then checkpoint_recovery rollback-bootstrap-pending; pki_publish_staged_file "$bootstrap_stage" "$bootstrap"; checkpoint_recovery rollback-bootstrap-done; fi
    if [[ ${PKI_RECORD[root_mutated]} == true ]]; then for key in "${db_keys[@]}"; do current=$(pki_file_identity_or_absent "${db_path[$key]}"); if [[ $current == "${PKI_RECORD[root_${key}_post_identity]}" && ${PKI_RECORD[root_${key}_pre_identity]} != "${PKI_RECORD[root_${key}_post_identity]}" ]]; then checkpoint_recovery "rollback-root-$key-pending"; pki_restore_journaled_file "${db_path[$key]}" "${PKI_RECORD[root_${key}_pre_identity]}" "${PKI_RECORD[root_${key}_post_identity]}" "${db_backup[$key]}" "${PKI_RECORD[root_${key}_backup_identity]}" "Root $key" || pki_die "Cannot restore root $key state"; checkpoint_recovery "rollback-root-$key-done"; fi; done; fi
  fi
  if [[ -d $authority ]]; then checkpoint_recovery rollback-authority-pending; pki_remove_journaled_tree "$authority" "$authority_identity" "$(dirname -- "$authority")" || pki_die 'Cannot remove journaled bootstrap authority'; checkpoint_recovery rollback-authority-done; fi
  if [[ $stage != none && -d $stage ]]; then checkpoint_recovery rollback-stage-pending; pki_remove_journaled_tree "$stage" "$stage_identity" "$(dirname -- "$stage")" || pki_die 'Cannot remove journaled bootstrap staging'; checkpoint_recovery rollback-stage-done; fi
  if [[ $(pki_file_identity_or_absent "$reservation") != "${PKI_RECORD[reservation_abandoned_identity]}" ]]; then checkpoint_recovery rollback-reservation-pending; pki_publish_staged_file "$abandoned_stage" "$reservation"; checkpoint_recovery rollback-reservation-done; fi
  PKI_RECORD[reservation_identity]=${PKI_RECORD[reservation_abandoned_identity]}; PKI_RECORD[recovery_step]=complete; write_loaded_journal rolled-back true
  rm -f -- "$MARKER"; pki_fsync "$(dirname -- "$MARKER")"; pki_ok "Rolled back bootstrap transaction: $TRANSACTION"; exit 0
fi
required_fields=(schema operation transaction phase legacy_root legacy_intermediate new_root new_intermediate root_source_identity intermediate_source_identity root_sha256 intermediate_sha256 transaction_dir transaction_identity provenance_stage provenance_dir provenance_identity provenance_manifest provenance_manifest_identity provenance_manifest_sha256 receipt_identity services_identity services_sha256 backup_receipt private_repo backup_session backup_session_original_identity backup_session_published_identity root_reservation root_reservation_original_identity root_reservation_reserved_identity root_reservation_consumed_identity root_reservation_rollback_identity intermediate_reservation intermediate_reservation_original_identity intermediate_reservation_reserved_identity intermediate_reservation_consumed_identity intermediate_reservation_rollback_identity root_config_original_identity root_config_published_identity root_config_rollback_identity root_config_backup_identity intermediate_config_original_identity intermediate_config_published_identity intermediate_config_rollback_identity intermediate_config_backup_identity issuer_ledger issuer_ledger_identity issuer_ledger_sha256 quarantine_ledger quarantine_ledger_identity quarantine_ledger_sha256 active_manifest active_original_identity active_published_identity committed)
for field in "${required_fields[@]}"; do [[ -v PKI_RECORD[$field] ]] || pki_die "Recovery journal is missing field: $field"; done
[[ ${PKI_RECORD[schema]} == 2 && ${PKI_RECORD[operation]} == legacy-migrate && ${PKI_RECORD[transaction]} == "$TRANSACTION" && ${PKI_RECORD[committed]} == false ]] || pki_die 'Recovery journal does not describe the requested uncommitted migration'
LEGACY_ROOT=${PKI_RECORD[legacy_root]}; LEGACY_INT=${PKI_RECORD[legacy_intermediate]}; NEW_ROOT=${PKI_RECORD[new_root]}; NEW_INT=${PKI_RECORD[new_intermediate]}; TXN_DIR=${PKI_RECORD[transaction_dir]}; ROOT_ID=${PKI_RECORD[root_source_identity]}; INT_ID=${PKI_RECORD[intermediate_source_identity]}
ROOT_RESERVATION=${PKI_RECORD[root_reservation]}; INT_RESERVATION=${PKI_RECORD[intermediate_reservation]}; BACKUP_SESSION=${PKI_RECORD[backup_session]}; ACTIVE_MANIFEST=${PKI_RECORD[active_manifest]}; ISSUER_LEDGER=${PKI_RECORD[issuer_ledger]}; QUARANTINE_LEDGER=${PKI_RECORD[quarantine_ledger]}
PROVENANCE_STAGE=${PKI_RECORD[provenance_stage]}; PROVENANCE_DIR=${PKI_RECORD[provenance_dir]}; PROVENANCE_IDENTITY=${PKI_RECORD[provenance_identity]}
[[ $LEGACY_ROOT == "$PKI_DIR/root-ca" && $LEGACY_INT == "$PKI_DIR/intermediate-ca" && $NEW_ROOT == "$PKI_DIR/authorities/roots/g1" && $NEW_INT == "$PKI_DIR/authorities/intermediates/g1-i1" && $TXN_DIR == "$PKI_DIR/state/rollover/$TRANSACTION" && $PROVENANCE_STAGE == "$PKI_DIR/legacy/.$TRANSACTION.publish" && $PROVENANCE_DIR == "$PKI_DIR/legacy/$TRANSACTION" && ${PKI_RECORD[provenance_manifest]} == "$PROVENANCE_STAGE/provenance-manifest" && $ROOT_RESERVATION == "$(pki_generation_reservation g1)" && $INT_RESERVATION == "$(pki_generation_reservation g1-i1)" && $ACTIVE_MANIFEST == "$(pki_active_issuer_manifest)" && $BACKUP_SESSION == "$PKI_DIR/state/rollover/backup-session-"* && $ISSUER_LEDGER == "$TXN_DIR/issuer-identities" && $QUARANTINE_LEDGER == "$TXN_DIR/quarantine-identities" ]] || pki_die 'Recovery journal paths are outside the exact migration contract'
[[ -d $TXN_DIR && ! -L $TXN_DIR && $(stat -c '%u:%a' "$TXN_DIR") == "$(id -u):700" && $(pki_dir_identity "$TXN_DIR") == "${PKI_RECORD[transaction_identity]}" ]] || pki_die 'Recovery transaction directory is missing, replaced, or unsafe'
[[ -d $PROVENANCE_STAGE && ! -L $PROVENANCE_STAGE && $(pki_dir_identity "$PROVENANCE_STAGE") == "$PROVENANCE_IDENTITY" && ! -e $PROVENANCE_DIR && ! -L $PROVENANCE_DIR || -d $PROVENANCE_DIR && ! -L $PROVENANCE_DIR && $(pki_dir_identity "$PROVENANCE_DIR") == "$PROVENANCE_IDENTITY" && ! -e $PROVENANCE_STAGE && ! -L $PROVENANCE_STAGE || ! -e $PROVENANCE_STAGE && ! -L $PROVENANCE_STAGE && ! -e $PROVENANCE_DIR && ! -L $PROVENANCE_DIR && ${PKI_RECORD[recovery_action]:-} == rollback && ${PKI_RECORD[recovery_step]:-} == rollback-provenance-* ]] || pki_die 'Migration provenance is missing, replaced, or ambiguous'
if [[ -d $PROVENANCE_STAGE ]]; then
  pki_validate_provenance_manifest "$PROVENANCE_STAGE" "${PKI_RECORD[provenance_manifest]}" "${PKI_RECORD[provenance_manifest_identity]}" "${PKI_RECORD[provenance_manifest_sha256]}"
elif [[ -d $PROVENANCE_DIR ]]; then
  pki_validate_provenance_manifest "$PROVENANCE_DIR" "$PROVENANCE_DIR/provenance-manifest" "${PKI_RECORD[provenance_manifest_identity]}" "${PKI_RECORD[provenance_manifest_sha256]}"
fi
pki_require_file_identity "${PKI_RECORD[backup_receipt]}" "${PKI_RECORD[receipt_identity]}" 'Migration backup receipt'
verify_bound_file() { local path=$1 identity=$2 digest=$3 label=$4 actual; pki_require_file_identity "$path" "$identity" "$label"; actual=$(sha256sum "$path"); [[ ${actual%% *} == "$digest" ]] || pki_die "$label digest changed"; }
verify_bound_file "$ISSUER_LEDGER" "${PKI_RECORD[issuer_ledger_identity]}" "${PKI_RECORD[issuer_ledger_sha256]}" 'Migration issuer ledger'
verify_bound_file "$QUARANTINE_LEDGER" "${PKI_RECORD[quarantine_ledger_identity]}" "${PKI_RECORD[quarantine_ledger_sha256]}" 'Migration quarantine ledger'
services_current=$(pki_file_identity_or_absent "$TXN_DIR/services")
[[ $services_current == "${PKI_RECORD[services_identity]}" || $services_current != absent && $(pki_file_identity "$TXN_DIR/services") == "${PKI_RECORD[services_identity]}" ]] || pki_die 'Recovery service set changed'
services_digest=$(sha256sum "$TXN_DIR/services"); [[ ${services_digest%% *} == "${PKI_RECORD[services_sha256]}" ]] || pki_die 'Recovery service set changed'

write_recovery_journal() {
  local phase=$1 committed=${2:-false} key value content=''
  PKI_RECORD[phase]=$phase; PKI_RECORD[committed]=$committed
  while IFS= read -r key; do value=${PKI_RECORD[$key]}; content+="$key=$value
"; done < <(printf '%s\n' "${!PKI_RECORD[@]}" | LC_ALL=C sort)
  pki_write_journal "$JOURNAL" "$content"
}
migration_checkpoint() { PKI_RECORD[recovery_action]=$ACTION; PKI_RECORD[recovery_step]=$1; write_recovery_journal recovering; recover_fault "$1"; }

authority_location() {
  local legacy=$1 generation=$2 identity=$3 label=$4 legacy_exists=false generation_exists=false
  [[ ! -e $legacy && ! -L $legacy ]] || legacy_exists=true; [[ ! -e $generation && ! -L $generation ]] || generation_exists=true
  [[ $legacy_exists != "$generation_exists" ]] || pki_die "$label paths are simultaneously present or absent"
  if [[ $legacy_exists == true ]]; then [[ -d $legacy && ! -L $legacy && $(stat -c '%d:%i' "$legacy") == "$identity" ]] || pki_die "$label legacy identity changed"; AUTHORITY_LOCATION=$legacy
  else [[ -d $generation && ! -L $generation && $(stat -c '%d:%i' "$generation") == "$identity" ]] || pki_die "$label generation identity changed"; AUTHORITY_LOCATION=$generation; fi
}

allowed_file_state() { local path=$1 label=$2; shift 2; local current expected; current=$(pki_file_identity_or_absent "$path"); for expected in "$@"; do [[ $current != "$expected" ]] || return 0; done; pki_die "$label is not in a journaled identity state"; }

# Validate every category before the first recovery mutation.
authority_location "$LEGACY_ROOT" "$NEW_ROOT" "$ROOT_ID" 'Root authority'; ROOT_LOCATION=$AUTHORITY_LOCATION
authority_location "$LEGACY_INT" "$NEW_INT" "$INT_ID" 'Intermediate authority'; INT_LOCATION=$AUTHORITY_LOCATION
allowed_file_state "$ROOT_LOCATION/openssl.cnf" 'Root OpenSSL configuration' "${PKI_RECORD[root_config_original_identity]}" "${PKI_RECORD[root_config_published_identity]}" "${PKI_RECORD[root_config_rollback_identity]}"
allowed_file_state "$INT_LOCATION/openssl.cnf" 'Intermediate OpenSSL configuration' "${PKI_RECORD[intermediate_config_original_identity]}" "${PKI_RECORD[intermediate_config_published_identity]}" "${PKI_RECORD[intermediate_config_rollback_identity]}"
allowed_file_state "$ROOT_RESERVATION" 'Root reservation' "${PKI_RECORD[root_reservation_original_identity]}" "${PKI_RECORD[root_reservation_reserved_identity]}" "${PKI_RECORD[root_reservation_consumed_identity]}" "${PKI_RECORD[root_reservation_rollback_identity]}"
allowed_file_state "$INT_RESERVATION" 'Intermediate reservation' "${PKI_RECORD[intermediate_reservation_original_identity]}" "${PKI_RECORD[intermediate_reservation_reserved_identity]}" "${PKI_RECORD[intermediate_reservation_consumed_identity]}" "${PKI_RECORD[intermediate_reservation_rollback_identity]}"
allowed_file_state "$BACKUP_SESSION" 'Backup session record' "${PKI_RECORD[backup_session_original_identity]}" "${PKI_RECORD[backup_session_published_identity]}"
allowed_file_state "$ACTIVE_MANIFEST" 'Active issuer manifest' "${PKI_RECORD[active_original_identity]}" "${PKI_RECORD[active_published_identity]}"
while IFS='|' read -r service original published extra; do [[ -n $service && -z ${extra:-} ]] || pki_die 'Migration issuer ledger has invalid content'; pki_validate_service_name "$service"; allowed_file_state "$(pki_service_issuer "$service")" "Service $service issuer" "$original" "$published"; done <"$ISSUER_LEDGER"
while IFS='|' read -r basename identity extra; do [[ $basename =~ ^(pki\.env|openssl-root\.cnf\.tpl|openssl-intermediate\.cnf\.tpl|openssl-service\.cnf\.tpl)$ && -z ${extra:-} ]] || pki_die 'Migration quarantine ledger has invalid content'; source="$PKI_DIR/$basename"; destination="$TXN_DIR/quarantine/$basename"; source_state=$(pki_file_identity_or_absent "$source"); destination_state=$(pki_file_identity_or_absent "$destination"); [[ $source_state == "$identity" && $destination_state == absent || $source_state == absent && $destination_state == "$identity" ]] || pki_die "Quarantine entry is ambiguous or replaced: $basename"; done <"$QUARANTINE_LEDGER"
if [[ $ACTION == rollback ]]; then
  [[ $(pki_file_identity_or_absent "$ROOT_LOCATION/openssl.cnf") != "${PKI_RECORD[root_config_published_identity]}" ]] || pki_require_file_identity "$TXN_DIR/root-openssl.rollback" "${PKI_RECORD[root_config_rollback_identity]}" 'Root OpenSSL rollback stage'
  [[ $(pki_file_identity_or_absent "$INT_LOCATION/openssl.cnf") != "${PKI_RECORD[intermediate_config_published_identity]}" ]] || pki_require_file_identity "$TXN_DIR/intermediate-openssl.rollback" "${PKI_RECORD[intermediate_config_rollback_identity]}" 'Intermediate OpenSSL rollback stage'
  [[ $(pki_file_identity_or_absent "$ROOT_RESERVATION") == "${PKI_RECORD[root_reservation_rollback_identity]}" ]] || pki_require_file_identity "$TXN_DIR/root-abandoned.publish" "${PKI_RECORD[root_reservation_rollback_identity]}" 'Root abandoned reservation stage'
  [[ $(pki_file_identity_or_absent "$INT_RESERVATION") == "${PKI_RECORD[intermediate_reservation_rollback_identity]}" ]] || pki_require_file_identity "$TXN_DIR/intermediate-abandoned.publish" "${PKI_RECORD[intermediate_reservation_rollback_identity]}" 'Intermediate abandoned reservation stage'
else
  [[ $(pki_file_identity_or_absent "$BACKUP_SESSION") != "${PKI_RECORD[backup_session_original_identity]}" ]] || pki_require_file_identity "$TXN_DIR/backup-session.publish" "${PKI_RECORD[backup_session_published_identity]}" 'Staged backup session'
  for record in "$ROOT_RESERVATION|${PKI_RECORD[root_reservation_original_identity]}|${PKI_RECORD[root_reservation_reserved_identity]}|${PKI_RECORD[root_reservation_consumed_identity]}|$TXN_DIR/root-reserved.publish|$TXN_DIR/root-consumed.publish" "$INT_RESERVATION|${PKI_RECORD[intermediate_reservation_original_identity]}|${PKI_RECORD[intermediate_reservation_reserved_identity]}|${PKI_RECORD[intermediate_reservation_consumed_identity]}|$TXN_DIR/intermediate-reserved.publish|$TXN_DIR/intermediate-consumed.publish"; do path=${record%%|*}; rest=${record#*|}; original=${rest%%|*}; rest=${rest#*|}; reserved=${rest%%|*}; rest=${rest#*|}; consumed=${rest%%|*}; rest=${rest#*|}; reserved_stage=${rest%%|*}; consumed_stage=${rest#*|}; current=$(pki_file_identity_or_absent "$path"); [[ $current != "$original" ]] || pki_require_file_identity "$reserved_stage" "$reserved" 'Staged reserved generation'; [[ $current == "$consumed" ]] || pki_require_file_identity "$consumed_stage" "$consumed" 'Staged consumed generation'; done
  [[ $(pki_file_identity_or_absent "$ROOT_LOCATION/openssl.cnf") != "${PKI_RECORD[root_config_original_identity]}" ]] || pki_require_file_identity "$TXN_DIR/root-openssl.new" "${PKI_RECORD[root_config_published_identity]}" 'Staged root generation configuration'
  [[ $(pki_file_identity_or_absent "$INT_LOCATION/openssl.cnf") != "${PKI_RECORD[intermediate_config_original_identity]}" ]] || pki_require_file_identity "$TXN_DIR/intermediate-openssl.new" "${PKI_RECORD[intermediate_config_published_identity]}" 'Staged intermediate generation configuration'
  while IFS='|' read -r service original published; do [[ $(pki_file_identity_or_absent "$(pki_service_issuer "$service")") != "$original" ]] || pki_require_file_identity "$TXN_DIR/issuer-stage/$service" "$published" "Staged issuer $service"; done <"$ISSUER_LEDGER"
  [[ $(pki_file_identity_or_absent "$ACTIVE_MANIFEST") != "${PKI_RECORD[active_original_identity]}" ]] || pki_require_file_identity "$TXN_DIR/active.publish" "${PKI_RECORD[active_published_identity]}" 'Staged active issuer'
fi

if [[ $ACTION == rollback ]]; then
  current=$(pki_file_identity_or_absent "$ACTIVE_MANIFEST"); if [[ $current == "${PKI_RECORD[active_published_identity]}" ]]; then migration_checkpoint rollback-active-pending; pki_remove_identity_file "$ACTIVE_MANIFEST" "$current" || pki_die 'Cannot remove journaled active issuer manifest'; migration_checkpoint rollback-active-done; fi
  while IFS='|' read -r service original published; do issuer=$(pki_service_issuer "$service"); current=$(pki_file_identity_or_absent "$issuer"); if [[ $current == "$published" ]]; then migration_checkpoint "rollback-issuer-$service-pending"; pki_remove_identity_file "$issuer" "$current" || pki_die "Cannot remove journaled issuer: $service"; migration_checkpoint "rollback-issuer-$service-done"; fi; done <"$ISSUER_LEDGER"
  while IFS='|' read -r basename identity; do source="$PKI_DIR/$basename"; destination="$TXN_DIR/quarantine/$basename"; if [[ $(pki_file_identity_or_absent "$destination") == "$identity" ]]; then migration_checkpoint "rollback-quarantine-$basename-pending"; pki_require_file_identity "$source" absent 'Quarantine restore destination'; mv -T -- "$destination" "$source"; pki_fsync_rename_parents "$(dirname -- "$destination")" "$(dirname -- "$source")"; pki_require_file_identity "$source" "$identity" 'Restored quarantine entry'; migration_checkpoint "rollback-quarantine-$basename-done"; fi; done <"$QUARANTINE_LEDGER"
  for record in "$ROOT_LOCATION|root|${PKI_RECORD[root_config_original_identity]}|${PKI_RECORD[root_config_published_identity]}|${PKI_RECORD[root_config_rollback_identity]}|$TXN_DIR/root-openssl.rollback" "$INT_LOCATION|intermediate|${PKI_RECORD[intermediate_config_original_identity]}|${PKI_RECORD[intermediate_config_published_identity]}|${PKI_RECORD[intermediate_config_rollback_identity]}|$TXN_DIR/intermediate-openssl.rollback"; do location=${record%%|*}; rest=${record#*|}; label=${rest%%|*}; rest=${rest#*|}; original=${rest%%|*}; rest=${rest#*|}; published=${rest%%|*}; rest=${rest#*|}; rollback=${rest%%|*}; stage=${rest#*|}; config="$location/openssl.cnf"; current=$(pki_file_identity_or_absent "$config"); if [[ $current == "$published" ]]; then migration_checkpoint "rollback-config-$label-pending"; pki_publish_staged_file "$stage" "$config"; migration_checkpoint "rollback-config-$label-done"; elif [[ $current != "$original" && $current != "$rollback" ]]; then pki_die "$label OpenSSL configuration changed before rollback"; fi; done
  authority_location "$LEGACY_INT" "$NEW_INT" "$INT_ID" 'Intermediate authority'; if [[ $AUTHORITY_LOCATION == "$NEW_INT" ]]; then migration_checkpoint rollback-intermediate-rename-pending; pki_require_file_identity "$LEGACY_INT" absent 'Legacy intermediate destination'; mv -T -- "$NEW_INT" "$LEGACY_INT"; pki_fsync_rename_parents "$(dirname -- "$NEW_INT")" "$(dirname -- "$LEGACY_INT")"; migration_checkpoint rollback-intermediate-rename-done; fi
  authority_location "$LEGACY_ROOT" "$NEW_ROOT" "$ROOT_ID" 'Root authority'; if [[ $AUTHORITY_LOCATION == "$NEW_ROOT" ]]; then migration_checkpoint rollback-root-rename-pending; pki_require_file_identity "$LEGACY_ROOT" absent 'Legacy root destination'; mv -T -- "$NEW_ROOT" "$LEGACY_ROOT"; pki_fsync_rename_parents "$(dirname -- "$NEW_ROOT")" "$(dirname -- "$LEGACY_ROOT")"; migration_checkpoint rollback-root-rename-done; fi
  for record in "$ROOT_RESERVATION|root|${PKI_RECORD[root_reservation_rollback_identity]}|$TXN_DIR/root-abandoned.publish" "$INT_RESERVATION|intermediate|${PKI_RECORD[intermediate_reservation_rollback_identity]}|$TXN_DIR/intermediate-abandoned.publish"; do path=${record%%|*}; rest=${record#*|}; kind=${rest%%|*}; rest=${rest#*|}; rollback=${rest%%|*}; stage=${rest#*|}; current=$(pki_file_identity_or_absent "$path"); if [[ $current != "$rollback" ]]; then migration_checkpoint "rollback-reservation-$kind-pending"; pki_publish_staged_file "$stage" "$path"; migration_checkpoint "rollback-reservation-$kind-done"; fi; done
  current=$(pki_file_identity_or_absent "$BACKUP_SESSION"); if [[ $current == "${PKI_RECORD[backup_session_published_identity]}" ]]; then migration_checkpoint rollback-backup-session-pending; pki_remove_identity_file "$BACKUP_SESSION" "$current" || pki_die 'Cannot remove backup session record'; migration_checkpoint rollback-backup-session-done; fi
  if [[ -d $PROVENANCE_STAGE ]]; then migration_checkpoint rollback-provenance-pending; pki_remove_journaled_tree "$PROVENANCE_STAGE" "$PROVENANCE_IDENTITY" "$(dirname -- "$PROVENANCE_STAGE")" || pki_die 'Cannot remove migration provenance stage'; migration_checkpoint rollback-provenance-done
  elif [[ -d $PROVENANCE_DIR ]]; then migration_checkpoint rollback-provenance-pending; pki_remove_journaled_tree "$PROVENANCE_DIR" "$PROVENANCE_IDENTITY" "$(dirname -- "$PROVENANCE_DIR")" || pki_die 'Cannot remove migration provenance'; migration_checkpoint rollback-provenance-done; fi
  write_recovery_journal rolled-back true; rm -f -- "$MARKER"; pki_fsync "$(dirname -- "$MARKER")"; pki_ok "Rolled back migration transaction: $TRANSACTION"; exit 0
fi

# Resume each mutation only from its exact original identity; exact published state is a no-op.
current=$(pki_file_identity_or_absent "$BACKUP_SESSION"); if [[ $current == "${PKI_RECORD[backup_session_original_identity]}" ]]; then migration_checkpoint resume-backup-session-pending; stage="$TXN_DIR/backup-session.publish"; pki_publish_staged_file "$stage" "$BACKUP_SESSION"; migration_checkpoint resume-backup-session-done; fi
for record in "$ROOT_RESERVATION|root|${PKI_RECORD[root_reservation_original_identity]}|${PKI_RECORD[root_reservation_reserved_identity]}|$TXN_DIR/root-reserved.publish" "$INT_RESERVATION|intermediate|${PKI_RECORD[intermediate_reservation_original_identity]}|${PKI_RECORD[intermediate_reservation_reserved_identity]}|$TXN_DIR/intermediate-reserved.publish"; do path=${record%%|*}; rest=${record#*|}; kind=${rest%%|*}; rest=${rest#*|}; original=${rest%%|*}; rest=${rest#*|}; published=${rest%%|*}; stage=${rest#*|}; current=$(pki_file_identity_or_absent "$path"); if [[ $current == "$original" ]]; then migration_checkpoint "resume-reservation-$kind-pending"; pki_publish_staged_file "$stage" "$path"; migration_checkpoint "resume-reservation-$kind-done"; elif [[ $current != "$published" && $current != "${PKI_RECORD[root_reservation_consumed_identity]}" && $current != "${PKI_RECORD[intermediate_reservation_consumed_identity]}" ]]; then pki_die 'Reservation cannot be resumed from its current identity'; fi; done
write_recovery_journal reserved
authority_location "$LEGACY_ROOT" "$NEW_ROOT" "$ROOT_ID" 'Root authority'; if [[ $AUTHORITY_LOCATION == "$LEGACY_ROOT" ]]; then migration_checkpoint resume-root-rename-pending; pki_require_file_identity "$NEW_ROOT" absent 'Root generation destination'; mv -T -- "$LEGACY_ROOT" "$NEW_ROOT"; pki_fsync_rename_parents "$(dirname -- "$LEGACY_ROOT")" "$(dirname -- "$NEW_ROOT")"; migration_checkpoint resume-root-rename-done; fi; write_recovery_journal root-renamed
authority_location "$LEGACY_INT" "$NEW_INT" "$INT_ID" 'Intermediate authority'; if [[ $AUTHORITY_LOCATION == "$LEGACY_INT" ]]; then migration_checkpoint resume-intermediate-rename-pending; pki_require_file_identity "$NEW_INT" absent 'Intermediate generation destination'; mv -T -- "$LEGACY_INT" "$NEW_INT"; pki_fsync_rename_parents "$(dirname -- "$LEGACY_INT")" "$(dirname -- "$NEW_INT")"; migration_checkpoint resume-intermediate-rename-done; fi; write_recovery_journal intermediate-renamed
for record in "$NEW_ROOT/openssl.cnf|root|${PKI_RECORD[root_config_original_identity]}|${PKI_RECORD[root_config_published_identity]}|$TXN_DIR/root-openssl.new" "$NEW_INT/openssl.cnf|intermediate|${PKI_RECORD[intermediate_config_original_identity]}|${PKI_RECORD[intermediate_config_published_identity]}|$TXN_DIR/intermediate-openssl.new"; do path=${record%%|*}; rest=${record#*|}; label=${rest%%|*}; rest=${rest#*|}; original=${rest%%|*}; rest=${rest#*|}; published=${rest%%|*}; stage=${rest#*|}; current=$(pki_file_identity_or_absent "$path"); if [[ $current == "$original" ]]; then migration_checkpoint "resume-config-$label-pending"; pki_publish_staged_file "$stage" "$path"; migration_checkpoint "resume-config-$label-done"; elif [[ $current != "$published" ]]; then pki_die 'Generation configuration cannot be resumed from its current identity'; fi; done
write_recovery_journal configs-published
while IFS='|' read -r service original published; do issuer=$(pki_service_issuer "$service"); stage="$TXN_DIR/issuer-stage/$service"; current=$(pki_file_identity_or_absent "$issuer"); if [[ $current == "$original" ]]; then migration_checkpoint "resume-issuer-$service-pending"; pki_publish_staged_file "$stage" "$issuer"; migration_checkpoint "resume-issuer-$service-done"; elif [[ $current != "$published" ]]; then pki_die "Issuer cannot be resumed from its current identity: $service"; fi; done <"$ISSUER_LEDGER"
write_recovery_journal issuers-published
while IFS='|' read -r basename identity; do source="$PKI_DIR/$basename"; destination="$TXN_DIR/quarantine/$basename"; if [[ $(pki_file_identity_or_absent "$source") == "$identity" ]]; then migration_checkpoint "resume-quarantine-$basename-pending"; pki_require_file_identity "$destination" absent 'Quarantine publication destination'; mv -T -- "$source" "$destination"; pki_fsync_rename_parents "$(dirname -- "$source")" "$(dirname -- "$destination")"; migration_checkpoint "resume-quarantine-$basename-done"; elif [[ $(pki_file_identity_or_absent "$destination") != "$identity" ]]; then pki_die "Quarantine entry cannot be resumed: $basename"; fi; done <"$QUARANTINE_LEDGER"
write_recovery_journal quarantined
for record in "$ROOT_RESERVATION|root|${PKI_RECORD[root_reservation_reserved_identity]}|${PKI_RECORD[root_reservation_consumed_identity]}|$TXN_DIR/root-consumed.publish" "$INT_RESERVATION|intermediate|${PKI_RECORD[intermediate_reservation_reserved_identity]}|${PKI_RECORD[intermediate_reservation_consumed_identity]}|$TXN_DIR/intermediate-consumed.publish"; do path=${record%%|*}; rest=${record#*|}; kind=${rest%%|*}; rest=${rest#*|}; reserved=${rest%%|*}; rest=${rest#*|}; consumed=${rest%%|*}; stage=${rest#*|}; current=$(pki_file_identity_or_absent "$path"); if [[ $current == "$reserved" ]]; then migration_checkpoint "resume-consume-$kind-pending"; pki_publish_staged_file "$stage" "$path"; migration_checkpoint "resume-consume-$kind-done"; elif [[ $current != "$consumed" ]]; then pki_die 'Reservation cannot be consumed from its current identity'; fi; done
write_recovery_journal active-pending
current=$(pki_file_identity_or_absent "$ACTIVE_MANIFEST"); if [[ $current == "${PKI_RECORD[active_original_identity]}" ]]; then migration_checkpoint resume-active-pending; stage="$TXN_DIR/active.publish"; pki_publish_staged_file "$stage" "$ACTIVE_MANIFEST"; migration_checkpoint resume-active-done; elif [[ $current != "${PKI_RECORD[active_published_identity]}" ]]; then pki_die 'Active issuer cannot be resumed from its current identity'; fi
if [[ -d $PROVENANCE_STAGE ]]; then migration_checkpoint resume-provenance-pending; mv -T -- "$PROVENANCE_STAGE" "$PROVENANCE_DIR"; pki_fsync_rename_parents "$(dirname -- "$PROVENANCE_STAGE")" "$(dirname -- "$PROVENANCE_DIR")"; [[ $(pki_dir_identity "$PROVENANCE_DIR") == "$PROVENANCE_IDENTITY" ]] || pki_die 'Migration provenance identity changed during recovery'; migration_checkpoint resume-provenance-done; fi
write_recovery_journal complete true; rm -f -- "$MARKER"; pki_fsync "$(dirname -- "$MARKER")"; pki_remove_journaled_tree "$TXN_DIR" "${PKI_RECORD[transaction_identity]}" "$(dirname -- "$TXN_DIR")" || pki_die 'Cannot remove committed migration transaction staging'; pki_ok "Resumed migration transaction: $TRANSACTION"
